CREATE TABLE "exercises" (
	"_id"	INTEGER,
	"name"	TEXT NOT NULL,
	"unit"	TEXT,
	"is_type_required"	INTEGER NOT NULL DEFAULT 0,
	PRIMARY KEY("_id" AUTOINCREMENT)
);

CREATE TABLE "process" (
	`_id`	INTEGER PRIMARY KEY AUTOINCREMENT,
	`_id_exercises`	INTEGER NOT NULL,
	`_id_types`	INTEGER NOT NULL,
	`value`	TEXT NOT NULL,
	`date`	TEXT NOT NULL
);

CREATE TABLE `types` (
	`_id`	INTEGER PRIMARY KEY AUTOINCREMENT,
	`_id_exercises`	INTEGER NOT NULL,
	`type`	TEXT NOT NULL
);

CREATE TABLE `weight` (
	`_id`	INTEGER PRIMARY KEY AUTOINCREMENT,
	`value`	REAL NOT NULL,
	`date`	TEXT
);

INSERT INTO "exercises" ("_id", "name", "unit", "is_type_required") VALUES
(1, 'Pull-ups', '', 1),
(2, 'Squats', '', 0),
(3, 'Exercise bike', 'min.', 0),
(4, 'Bicycle', 'min.', 0),
(5, 'Push-ups', '', 0),
(6, 'Dumbbell lateral raises standing', '', 1),
(7, 'Dumbbell bicep curls standing', '', 1),
(8, 'Abs', '', 0),
(9, 'Calf raises', '', 0),
(10, 'Dumbbell side bends', '', 1),
(11, 'Jump rope', '', 0),
(12, 'Stretching', 'sec.', 0),
(13, 'Warm-up', 'min.', 0),
(14, 'Hiking', 'km', 0),
(15, 'Arm trainer (each arm)', '', 0),
(16, 'Dumbbell flyes lying', '', 1),
(17, 'Plank', 'sec.', 0),
(18, 'Walking', 'km', 0),
(19, 'Hanging on pull-up bar', 'sec.', 0),
(20, 'Strange exercise', 'min.', 0),
(21, 'Step-ups', '', 0),
(22, 'Burpees', '', 0),
(23, 'Running', 'min.', 0),
(24, 'Hanging leg raises', '', 0),
(25, 'Frozen V-Sit', 'sec.', 0),
(26, 'Mountain climber', '', 0),
(27, 'Jump lunges', '', 0),
(28, 'French press standing', '', 1),
(29, 'Dumbbell wrist curls', '', 1),
(30, 'Dumbbell front raises', '', 1),
(31, 'Wall sit', 'sec.', 0),
(32, 'Dumbbell snatch', '', 1),
(33, 'Leg raises 4-count', '', 0),
(34, 'Barbell press', '', 1),
(35, 'Distance running', 'm', 0),
(36, 'Sprint running', 'sec.', 0),
(37, 'Dips', '', 0),
(38, 'Dip bar abs', '', 0),
(39, 'Steps', '', 0),
(40, 'Negative pyramid', 'sec.', 0),
(41, 'Shoulder taps with feet on chair', '', 0),
(42, 'Oculus Move', 'kcal', 0),
(43, 'Sumo squats', '', 0),
(44, 'Side swings', '', 0),
(45, 'Glute bridge', '', 0),
(46, 'Volleyball', 'min.', 0),
(47, 'Badminton', 'min.', 0),
(48, 'Dumbbell upright rows', '', 1);

INSERT INTO "types" ("_id", "_id_exercises", "type") VALUES
(1, 1, 'With swinging'),
(2, 1, 'With jerking'),
(4, 6, '9 kg'),
(5, 7, '9 kg'),
(6, 10, '9 kg'),
(7, 1, 'Reverse grip with jerking'),
(8, 1, 'Reverse grip with swinging'),
(10, 5, 'From nightstand'),
(11, 8, 'On stool'),
(12, 5, 'On supports'),
(13, 16, '9 kg'),
(16, 1, 'No jerking, but last ones with jerking'),
(17, 1, 'Reverse grip without jerking'),
(18, 11, 'On one leg'),
(19, 1, 'Without jerking'),
(20, 23, 'In apartment'),
(21, 1, 'Reverse grip without full arm extension'),
(22, 24, 'Straight legs to 90 degrees'),
(23, 28, 'Both hands 9 kg'),
(24, 29, 'Both hands together 9 kg'),
(25, 28, '9 kg one hand'),
(26, 5, 'Wide grip'),
(27, 5, 'Wide grip on supports'),
(28, 5, 'Narrow grip'),
(29, 5, 'With clap'),
(30, 1, 'Wide grip without jerking, but last ones with jerking'),
(31, 1, 'Narrow grip without jerking, but last ones with jerking'),
(32, 1, 'Narrow grip with jerking'),
(33, 1, 'Wide grip with jerking'),
(34, 5, 'Narrow grip on supports'),
(35, 1, 'Narrow grip without jerking'),
(36, 1, 'Wide grip without jerking'),
(39, 11, 'Accelerated'),
(40, 5, 'To the floor'),
(41, 1, 'Completely clean'),
(42, 5, 'On fists'),
(43, 30, 'One hand 9 kg'),
(44, 8, 'On floor with leg fixation'),
(45, 17, 'On extended arms'),
(46, 1, 'On one hand, holding with the other'),
(47, 5, 'On knees'),
(48, 32, '9 kg'),
(49, 24, 'To the bar'),
(50, 21, '9 kg in each hand'),
(51, 34, '70 kg'),
(52, 9, '9 kg in each hand'),
(53, 36, 'In place'),
(54, 30, 'One hand 6.5 kg'),
(55, 6, '11.5 kg'),
(56, 7, '11.5 kg'),
(57, 28, '6.5 kg one hand'),
(58, 16, '6.5 kg'),
(59, 7, '6.5 kg'),
(60, 6, '14 kg'),
(61, 7, '14 kg'),
(62, 5, 'Pike push-ups'),
(63, 5, 'Pseudo planche push-ups'),
(64, 17, 'Pseudo planche hold'),
(65, 29, '9 kg in each hand'),
(66, 9, '11.5 kg in each hand'),
(67, 10, '11.5 kg'),
(68, 29, '6.5 kg in each hand'),
(69, 6, '6.5 kg'),
(70, 48, '6.5 kg'),
(71, 48, '9 kg'),
(72, 28, 'Both hands 6.5 kg'),
(73, 10, '6.5 kg');
