CREATE TABLE "exercises" (
	"_id"	INTEGER,
	"name"	TEXT NOT NULL,
	"unit"	TEXT,
	"is_type_required"	INTEGER NOT NULL DEFAULT 0,
	calories_per_unit REAL DEFAULT 0,
	PRIMARY KEY("_id" AUTOINCREMENT)
);

CREATE TABLE "process" (
	`_id`	INTEGER PRIMARY KEY AUTOINCREMENT,
	`_id_exercises`	INTEGER NOT NULL,
	`_id_types`	INTEGER NOT NULL,
	`value`	TEXT NOT NULL,
	`date`	TEXT NOT NULL
);

CREATE TABLE `types` (
	`_id`	INTEGER PRIMARY KEY AUTOINCREMENT,
	`_id_exercises`	INTEGER NOT NULL,
	`type`	TEXT NOT NULL,
	calories_modifier REAL DEFAULT 1.0
);

CREATE TABLE `weight` (
	`_id`	INTEGER PRIMARY KEY AUTOINCREMENT,
	`value`	REAL NOT NULL,
	`date`	TEXT
);

CREATE TABLE "food_items" (
    "_id" INTEGER PRIMARY KEY AUTOINCREMENT,
    "name" TEXT NOT NULL,
    "name_en" TEXT,
    "is_drink" INTEGER NOT NULL DEFAULT 0,
    "calories_per_100g" REAL DEFAULT NULL,
    "default_portion_weight" REAL DEFAULT NULL,
    "default_portion_calories" REAL DEFAULT NULL
);

CREATE TABLE "food_log" (
    "_id" INTEGER PRIMARY KEY AUTOINCREMENT,
    "date" TEXT NOT NULL,
    "weight" REAL DEFAULT NULL,
    "portion_calories" REAL DEFAULT NULL,
    "calculated_calories" REAL NOT NULL,
    "name" TEXT DEFAULT NULL,
    "name_en" TEXT DEFAULT NULL
);

INSERT INTO "exercises" ("_id", "name", "unit", "is_type_required", "calories_per_unit") VALUES
(1, 'Pull-ups', '', 1, 0.5),
(2, 'Squats', '', 0, 0.5),
(3, 'Exercise bike', 'min.', 0, 8.0),
(4, 'Bicycle', 'min.', 0, 8.0),
(5, 'Push-ups', '', 0, 0.5),
(6, 'Dumbbell lateral raises standing', '', 1, 0.4),
(7, 'Dumbbell bicep curls standing', '', 1, 0.4),
(8, 'Abs', '', 0, 0.3),
(9, 'Calf raises', '', 0, 0.3),
(10, 'Dumbbell side bends', '', 1, 0.4),
(11, 'Jump rope', '', 0, 6.0),
(12, 'Stretching', 'sec.', 0, 0.1),
(13, 'Warm-up', 'sec.', 0, 0.1),
(14, 'Hiking', 'km', 0, 12.0),
(15, 'Arm trainer (each arm)', '', 0, 0.2),
(16, 'Dumbbell flyes lying', '', 1, 0.4),
(17, 'Plank', 'sec.', 0, 0.1),
(18, 'Walking', 'm', 0, 0.05),
(19, 'Hanging on pull-up bar', 'sec.', 0, 0.1),
(20, 'Strange exercise', 'min.', 0, 5.0),
(21, 'Step-ups', '', 0, 0.4),
(22, 'Burpees', '', 0, 0.5),
(23, 'Running', 'min.', 0, 8.0),
(24, 'Hanging leg raises', '', 0, 0.3),
(25, 'Frozen V-Sit', 'sec.', 0, 0.1),
(26, 'Mountain climber', '', 0, 0.4),
(27, 'Jump lunges', '', 0, 0.4),
(28, 'French press standing', '', 1, 0.4),
(29, 'Dumbbell wrist curls', '', 1, 0.4),
(30, 'Dumbbell front raises', '', 1, 0.4),
(31, 'Wall sit', 'sec.', 0, 0.1),
(32, 'Dumbbell snatch', '', 1, 0.4),
(33, 'Leg raises 4-count', '', 0, 0.3),
(34, 'Barbell press', '', 1, 0.4),
(35, 'Distance running', 'm', 0, 0.08),
(36, 'Sprint running', 'sec.', 0, 10.0),
(37, 'Dips', '', 0, 0.5),
(38, 'Dip bar abs', '', 0, 0.2),
(39, 'Steps', '', 0, 0.1),
(40, 'Negative pyramid', 'sec.', 0, 0.05),
(41, 'Shoulder taps with feet on chair', '', 0, 0.2),
(42, 'Oculus Move', 'kcal', 0, 1.0),
(43, 'Sumo squats', '', 0, 0.4),
(44, 'Side swings', '', 0, 0.2),
(45, 'Glute bridge', '', 0, 0.4),
(46, 'Volleyball', 'min.', 0, 8.0),
(47, 'Badminton', 'min.', 0, 8.0),
(48, 'Dumbbell upright rows', '', 1, 0.4),
(50, 'Monkey bars', '', 0, 0.3);

INSERT INTO "types" ("_id", "_id_exercises", "type", "calories_modifier") VALUES
(1, 1, 'With swinging', 1.2),
(2, 1, 'With jerking', 1.2),
(4, 6, '9 kg', 1.2),
(5, 7, '9 kg', 1.2),
(6, 10, '9 kg', 1.2),
(7, 1, 'Reverse grip with jerking', 1.1),
(8, 1, 'Reverse grip with swinging', 1.1),
(10, 5, 'From nightstand', 1.1),
(11, 8, 'On stool', 1.1),
(12, 5, 'On supports', 1.1),
(13, 16, '9 kg', 1.2),
(16, 1, 'No jerking, but last ones with jerking', 1.2),
(17, 1, 'Reverse grip without jerking', 1.1),
(18, 11, 'On one leg', 1.2),
(19, 1, 'Without jerking', 1.2),
(20, 23, 'In apartment', 1.0),
(21, 1, 'Reverse grip without full arm extension', 1.1),
(22, 24, 'Straight legs to 90 degrees', 1.3),
(23, 28, 'Both hands 9 kg', 1.2),
(24, 29, 'Both hands together 9 kg', 1.2),
(25, 28, '9 kg one hand', 1.2),
(26, 5, 'Wide grip', 1.3),
(27, 5, 'Wide grip on supports', 1.3),
(28, 5, 'Narrow grip', 1.2),
(29, 5, 'With clap', 1.4),
(30, 1, 'Wide grip without jerking, but last ones with jerking', 1.3),
(31, 1, 'Narrow grip without jerking, but last ones with jerking', 0.9),
(32, 1, 'Narrow grip with jerking', 0.9),
(33, 1, 'Wide grip with jerking', 1.3),
(34, 5, 'Narrow grip on supports', 0.9),
(35, 1, 'Narrow grip without jerking', 0.9),
(36, 1, 'Wide grip without jerking', 1.3),
(39, 11, 'Accelerated', 1.2),
(40, 5, 'To the floor', 1.0),
(41, 1, 'Completely clean', 1.4),
(42, 5, 'On fists', 1.2),
(43, 30, 'One hand 9 kg', 1.2),
(44, 8, 'On floor with leg fixation', 1.1),
(45, 17, 'On extended arms', 1.2),
(46, 1, 'On one hand, holding with the other', 1.5),
(47, 5, 'On knees', 0.8),
(48, 32, '9 kg', 1.2),
(49, 24, 'To the bar', 1.1),
(50, 21, '9 kg in each hand', 1.2),
(51, 34, '70 kg', 1.8),
(52, 9, '9 kg in each hand', 1.2),
(53, 36, 'In place', 1.2),
(54, 30, 'One hand 6.5 kg', 1.0),
(55, 6, '11.5 kg', 1.4),
(56, 7, '11.5 kg', 1.4),
(57, 28, '6.5 kg one hand', 1.0),
(58, 16, '6.5 kg', 1.0),
(59, 7, '6.5 kg', 1.0),
(60, 6, '14 kg', 1.5),
(61, 7, '14 kg', 1.5),
(62, 5, 'Pike push-ups', 1.5),
(63, 5, 'Pseudo planche push-ups', 1.8),
(64, 17, 'Pseudo planche hold', 1.3),
(65, 29, '9 kg in each hand', 1.2),
(66, 9, '11.5 kg in each hand', 1.4),
(67, 10, '11.5 kg', 1.4),
(68, 29, '6.5 kg in each hand', 1.0),
(69, 6, '6.5 kg', 1.0),
(70, 48, '6.5 kg', 1.0),
(71, 48, '9 kg', 1.2),
(72, 28, 'Both hands 6.5 kg', 1.0),
(73, 10, '6.5 kg', 1.0),
(74, 34, 'In park', 1.1),
(75, 9, '6.5 kg in each hand', 1.0);

INSERT INTO food_items (name, name_en, is_drink, calories_per_100g, default_portion_weight, default_portion_calories) VALUES
('Абрикос', 'Apricot', 0, 48, NULL, NULL),
('Ананас', 'Pineapple', 0, 50, NULL, NULL),
('Апельсин', 'Orange', 0, 43, NULL, NULL),
('Арахис', 'Peanuts', 0, 567, NULL, NULL),
('Арбуз', 'Watermelon', 0, 30, NULL, NULL),
('Базилик', 'Basil', 0, 22, NULL, NULL),
('Банан', 'Banana', 0, 89, NULL, NULL),
('Бекон жареный', 'Fried bacon', 0, 468, NULL, NULL),
('Борщ', 'Borscht', 0, 49, NULL, NULL),
('Виноград кишмиш белый', 'White grapes', 0, 40, NULL, NULL),
('Глинтвейн', 'Mulled wine', 1, 132, NULL, NULL),
('Говядина', 'Beef', 0, 250, NULL, NULL),
('Говядина вареная', 'Boiled beef', 0, 254, NULL, NULL),
('Голубика', 'Blueberry', 0, 57, NULL, NULL),
('Горошек', 'Peas', 0, 50, NULL, NULL),
('Грейпфрут', 'Grapefruit', 0, 42, NULL, NULL),
('Гречка вареная', 'Boiled buckwheat', 0, 88, NULL, NULL),
('Груша', 'Pear', 0, 57, NULL, NULL),
('Дыня Колхозница', 'Kolkhoznitsa melon', 0, 39, NULL, NULL),
('Дыня Торпеда', 'Torpedo melon', 0, 34, NULL, NULL),
('Жаркое с курицей', 'Chicken stew', 0, 113, NULL, NULL),
('Жимолость', 'Honeysuckle', 0, 30, NULL, NULL),
('Зефир в шоколаде', 'Chocolate marshmallow', 0, 396, 30, NULL),
('Индейка вареная', 'Boiled turkey', 0, 130, NULL, NULL),
('Кабачок', 'Zucchini', 0, 24, NULL, NULL),
('Какао порошок', 'Cocoa powder', 0, 228, NULL, NULL),
('Капуста', 'Cabbage', 0, 25, NULL, NULL),
('Капуста краснокочанная', 'Red cabbage', 0, 31, NULL, NULL),
('Картофельное пюре', 'Mashed potatoes', 0, 88, NULL, NULL),
('Картошка', 'Potatoes', 0, 77, NULL, NULL),
('Картошка вареная', 'Boiled potatoes', 0, 82, NULL, NULL),
('Киви', 'Kiwi', 0, 61, NULL, NULL),
('Клубника', 'Strawberry', 0, 33, NULL, NULL),
('Кокос мякоть', 'Coconut meat', 0, 354, NULL, NULL),
('Кокосовая стружка', 'Coconut flakes', 0, 660, NULL, NULL),
('Кофе Капучино без сахара', 'Cappuccino no sugar', 1, 53, NULL, NULL),
('Кофе Латте', 'Latte', 1, 44, NULL, NULL),
('Кофе Флэт Уайт', 'Flat White', 1, 42, NULL, NULL),
('Курица вареная', 'Boiled chicken', 0, 170, NULL, NULL),
('Курица филе', 'Chicken breast', 0, 110, NULL, NULL),
('Лимон', 'Lemon', 0, 29, NULL, NULL),
('Лук зеленый', 'Green onion', 0, 19, NULL, NULL),
('Лук репчатый', 'Onion', 0, 40, NULL, NULL),
('Макароны отварные', 'Boiled pasta', 0, 112, NULL, NULL),
('Малина', 'Raspberry', 0, 53, NULL, NULL),
('Манго', 'Mango', 0, 70, NULL, NULL),
('Мандарин', 'Mandarin', 0, 53, NULL, NULL),
('Маракуйя', 'Passion fruit', 0, 97, NULL, NULL),
('Масло оливковое', 'Olive oil', 0, 884, NULL, NULL),
('Масло сливочное', 'Butter', 0, 750, NULL, NULL),
('Морковь', 'Carrot', 0, 32, NULL, NULL),
('Морковь вареная', 'Boiled carrot', 0, 35, NULL, NULL),
('Морс', 'Fruit drink', 1, 52, NULL, NULL),
('Несквик', 'Nesquik', 0, 379, NULL, NULL),
('Овсянка', 'Oatmeal', 0, 102, NULL, NULL),
('Огурцы', 'Cucumber', 0, 15, NULL, NULL),
('Окорочок гриль', 'Grilled chicken leg', 0, 181, NULL, NULL),
('Орех арахис', 'Peanuts', 0, 567, NULL, NULL),
('Орех бразильский', 'Brazil nuts', 0, 656, NULL, NULL),
('Орех грецкий', 'Walnuts', 0, 654, NULL, NULL),
('Орех кедровый', 'Pine nuts', 0, 680, NULL, NULL),
('Орех кешью', 'Cashew nuts', 0, 553, NULL, NULL),
('Орех макадамия', 'Macadamia nuts', 0, 718, NULL, NULL),
('Орех миндаль', 'Almonds', 0, 649, NULL, NULL),
('Орех пекан', 'Pecan nuts', 0, 691, NULL, NULL),
('Орех фисташки', 'Pistachios', 0, 562, NULL, NULL),
('Орех фундук', 'Hazelnuts', 0, 628, NULL, NULL),
('Перец болгарский', 'Bell pepper', 0, 27, NULL, NULL),
('Перец острый', 'Hot pepper', 0, 40, NULL, NULL),
('Персик', 'Peach', 0, 39, NULL, NULL),
('Персики плоские инжирные', 'Flat peaches', 0, 60, NULL, NULL),
('Петрушка', 'Parsley', 0, 47, NULL, NULL),
('Печенье Юбилейное', 'Jubilee cookies', 0, NULL, NULL, 52),
('Пицца', 'Pizza', 0, 266, NULL, NULL),
('Помидоры', 'Tomatoes', 0, 20, NULL, NULL),
('Растительное масло', 'Vegetable oil', 0, 899, NULL, NULL),
('Редис', 'Radish', 0, 16, NULL, NULL),
('Редька зеленая', 'Green radish', 0, 32, NULL, NULL),
('Рис вареный', 'Boiled rice', 0, 116, NULL, NULL),
('Салат айсберг', 'Iceberg lettuce', 0, 14, NULL, NULL),
('Салат латук', 'Lettuce', 0, 15, NULL, NULL),
('Салат Оливье', 'Olivier salad', 0, 160, NULL, NULL),
('Салат Столичный', 'Capital salad', 0, 217, NULL, NULL),
('Сахар', 'Sugar', 0, 387, NULL, NULL),
('Свекла', 'Beetroot', 0, 43, NULL, NULL),
('Свинина', 'Pork', 0, 242, NULL, NULL),
('Сгущенка', 'Condensed milk', 0, 330, NULL, NULL),
('Слива', 'Plum', 0, 46, NULL, NULL),
('Сливки 10%', 'Cream 10%', 1, 119, NULL, NULL),
('Сливки 20%', 'Cream 20%', 1, 205, NULL, NULL),
('Сосиска в тесте', 'Sausage in dough', 0, 287, NULL, NULL),
('Соус тартар', 'Tartar sauce', 0, 340, NULL, NULL),
('Стейк миньон', 'Filet mignon', 0, 267, NULL, NULL),
('Стейк рибай', 'Ribeye steak', 0, 291, NULL, NULL),
('Творог 0,5%', 'Cottage cheese 0.5%', 0, 90, NULL, NULL),
('Творог 2%', 'Cottage cheese 2%', 0, 103, NULL, NULL),
('Тефтели', 'Meatballs', 0, 197, NULL, NULL),
('Укроп', 'Dill', 0, 38, NULL, NULL),
('Уксус', 'Vinegar', 0, 18, NULL, NULL),
('Финики', 'Dates', 0, 282, NULL, NULL),
('Харчо', 'Kharcho soup', 0, 44, NULL, NULL),
('Хинкали', 'Khinkali', 0, 234, NULL, NULL),
('Хурма', 'Persimmon', 0, 127, NULL, NULL),
('Черешня', 'Cherry', 0, 50, NULL, NULL),
('Черная смородина', 'Black currant', 0, 44, NULL, NULL),
('Чеснок', 'Garlic', 0, 143, NULL, NULL),
('Шампиньоны', 'Mushrooms', 0, 22, NULL, NULL),
('Шаурма', 'Shawarma', 0, 174, NULL, NULL),
('Шаурма с говядиной', 'Beef shawarma', 0, 192, NULL, NULL),
('Шашлык из курицы', 'Chicken kebab', 0, 142, NULL, NULL),
('Шашлык из свинины', 'Pork kebab', 0, 326, NULL, NULL),
('Шпинат зеленый', 'Green spinach', 0, 22, NULL, NULL),
('Яблоко', 'Apple', 0, 47, NULL, NULL),
('Яйцо вареное', 'Boiled egg', 0, 155, NULL, NULL);
