-- Recover / recreate Food database schema and seed data
-- Schema matches the live app (food_items / food_log use `_id`; food_log stores `date`
-- and portion / per-100g calories). Seed is food_items catalog only; food_log stays empty.

PRAGMA foreign_keys = OFF;

DROP TABLE IF EXISTS recipe_ingredients;
DROP TABLE IF EXISTS recipes;
DROP TABLE IF EXISTS food_log;
DROP TABLE IF EXISTS food_items;

PRAGMA foreign_keys = ON;

CREATE TABLE food_items (
    _id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL UNIQUE,
    name_en TEXT,
    is_drink INTEGER NOT NULL DEFAULT 0 CHECK (is_drink IN (0, 1)),
    calories_per_100g REAL,
    default_portion_weight REAL,
    default_portion_calories REAL
);

CREATE TABLE food_log (
    _id INTEGER PRIMARY KEY AUTOINCREMENT,
    date TEXT,
    weight REAL,
    portion_calories REAL,
    calories_per_100g REAL,
    name TEXT,
    name_en TEXT,
    is_drink INTEGER NOT NULL DEFAULT 0 CHECK (is_drink IN (0, 1))
);

CREATE TABLE recipes (
    _id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL UNIQUE,
    name_en TEXT,
    is_drink INTEGER NOT NULL DEFAULT 0 CHECK (is_drink IN (0, 1)),
    calories_per_100g REAL,
    total_weight REAL
);

CREATE TABLE recipe_ingredients (
    _id INTEGER PRIMARY KEY AUTOINCREMENT,
    recipe_id INTEGER NOT NULL,
    name TEXT NOT NULL,
    name_en TEXT,
    weight REAL,
    calories_per_100g REAL,
    portion_calories REAL,
    is_drink INTEGER NOT NULL DEFAULT 0 CHECK (is_drink IN (0, 1)),
    sort_order INTEGER NOT NULL DEFAULT 0,
    FOREIGN KEY (recipe_id) REFERENCES recipes(_id) ON DELETE CASCADE
);

-- Seed catalog of food items from working database
INSERT INTO food_items (name, name_en, is_drink, calories_per_100g, default_portion_weight, default_portion_calories) VALUES
('Абрикос', 'Apricot', 0, 48, NULL, NULL),
('Абрикос сушеный', 'Dried apricot', 0, 215, NULL, NULL),
('Абсент', 'Absinthe', 1, 195, 30, NULL),
('Авокадо', 'Avocado', 0, 160, NULL, NULL),
('Авокадо хасс', 'Hass avocado', 0, 167, NULL, NULL),
('Агар-агар', 'Agar-agar', 0, 26, NULL, NULL),
('Аджика', 'Adjika', 0, 60, NULL, NULL),
('Аджика сухая', 'Dry adjika', 0, 200, NULL, NULL),
('Айва', 'Quince', 0, 57, NULL, NULL),
('Айран', 'Ayran', 1, 24, 250, NULL),
('Актинидия', 'Hardy kiwi', 0, 61, NULL, NULL),
('Алоэ вера мякоть', 'Aloe vera pulp', 0, 4, NULL, NULL),
('Алыча', 'Cherry plum', 0, 34, NULL, NULL),
('Амаретто', 'Amaretto', 1, 270, 40, NULL),
('Американо', 'Americano', 1, 2, 200, NULL),
('Амла', 'Amla', 0, 44, NULL, NULL),
('Ананас', 'Pineapple', 0, 50, NULL, NULL),
('Ананас консервированный', 'Canned pineapple', 0, 60, NULL, NULL),
('Анис', 'Anise', 0, 337, NULL, NULL),
('Анчоусы', 'Anchovies', 0, 210, NULL, NULL),
('Анчоусы в масле', 'Anchovies in oil', 0, 250, NULL, NULL),
('Апельсин', 'Orange', 0, 43, NULL, NULL),
('Апельсиновая цедра', 'Orange zest', 0, 97, NULL, NULL),
('Апельсины кровавые', 'Blood orange', 0, 50, NULL, NULL),
('Арахис', 'Peanuts', 0, 567, NULL, NULL),
('Арахисовая паста', 'Peanut butter', 0, 588, NULL, NULL),
('Арбуз', 'Watermelon', 0, 30, NULL, NULL),
('Арбуз желтый', 'Yellow watermelon', 0, 30, NULL, NULL),
('Артишок', 'Artichoke', 0, 47, NULL, NULL),
('Артишок иерусалимский', 'Jerusalem artichoke', 0, 61, NULL, NULL),
('Асаи', 'Acai', 0, 70, NULL, NULL),
('БАО булочка', 'Bao bun', 0, 220, NULL, NULL),
('Багет', 'Baguette', 0, 274, NULL, NULL),
('Бадьян', 'Star anise', 0, 337, NULL, NULL),
('Базилик', 'Basil', 0, 22, NULL, NULL),
('Базилик сушеный', 'Dried basil', 0, 233, NULL, NULL),
('Баклажан', 'Eggplant', 0, 24, NULL, NULL),
('Баклажан белый', 'White eggplant', 0, 24, NULL, NULL),
('Баклажан жареный', 'Fried eggplant', 0, 120, NULL, NULL),
('Баклажаны по-сычуаньски', 'Sichuan eggplant', 0, 100, NULL, NULL),
('Балык', 'Balyk', 0, 190, NULL, NULL),
('Балык из лосося', 'Salmon balyk', 0, 195, NULL, NULL),
('Балык из осетра', 'Sturgeon balyk', 0, 200, NULL, NULL),
('Бамбуковые ростки', 'Bamboo shoots', 0, 27, NULL, NULL),
('Банан', 'Banana', 0, 89, NULL, NULL),
('Банан зеленый', 'Green banana', 0, 89, NULL, NULL),
('Банан красный', 'Red banana', 0, 90, NULL, NULL),
('Бань бао', 'Banh bao', 0, 200, NULL, NULL),
('Бань ксео', 'Banh xeo', 0, 180, NULL, NULL),
('Бань куон', 'Banh cuon', 0, 120, NULL, NULL),
('Бань ми', 'Banh mi', 0, 220, NULL, NULL),
('Бань ми с курицей', 'Chicken banh mi', 0, 210, NULL, NULL),
('Бань ми с свининой', 'Pork banh mi', 0, 230, NULL, NULL),
('Бань тет', 'Banh tet', 0, 180, NULL, NULL),
('Бань чунг', 'Banh chung', 0, 180, NULL, NULL),
('Баранина', 'Lamb', 0, 209, NULL, NULL),
('Баранки', 'Baranki', 0, 340, NULL, NULL),
('Барбарис', 'Barberry', 0, 29, NULL, NULL),
('Барбарис сушеный', 'Dried barberry', 0, 29, NULL, NULL),
('Батат', 'Sweet potato', 0, 86, NULL, NULL),
('Батон нарезной', 'Sliced loaf', 0, 264, NULL, NULL),
('Батончик шоколадный', 'Chocolate bar', 0, 500, NULL, NULL),
('Баунти', 'Bounty', 0, 470, 57, NULL),
('Бейлис', 'Baileys', 1, 327, 50, NULL),
('Бекон жареный', 'Fried bacon', 0, 468, NULL, NULL),
('Белуга', 'Beluga', 0, 148, NULL, NULL),
('Белые грибы', 'Porcini mushrooms', 0, 34, NULL, NULL),
('Беляш', 'Belyash', 0, 310, NULL, NULL),
('Бергамот', 'Bergamot', 0, 45, NULL, NULL),
('Бефстроганов', 'Beef stroganoff', 0, 177, NULL, NULL),
('Блади Мэри', 'Bloody Mary', 1, 50, 200, NULL),
('Блинчики рисовые вьетнамские', 'Vietnamese rice crepes', 0, 120, NULL, NULL),
('Блины', 'Pancakes', 0, 233, NULL, NULL),
('Блины с икрой', 'Pancakes with caviar', 0, 250, NULL, NULL),
('Блины с красной икрой', 'Pancakes with red caviar', 0, 260, NULL, NULL),
('Блины с мясом', 'Pancakes with meat', 0, 230, NULL, NULL),
('Блины с творогом', 'Pancakes with cottage cheese', 0, 210, NULL, NULL),
('Блины со сметаной', 'Pancakes with sour cream', 0, 220, NULL, NULL),
('Бок-чой', 'Bok choy', 0, 13, NULL, NULL),
('Борщ', 'Borscht', 0, 49, NULL, NULL),
('Борщ со сметаной', 'Borscht with sour cream', 0, 60, NULL, NULL),
('Борщ украинский', 'Ukrainian borscht', 0, 50, NULL, NULL),
('Боярышник', 'Hawthorn', 0, 52, NULL, NULL),
('Бренди', 'Brandy', 1, 239, 50, NULL),
('Брокколи', 'Broccoli', 0, 34, NULL, NULL),
('Брусника', 'Lingonberry', 0, 46, NULL, NULL),
('Брынза', 'Bryndza', 0, 260, NULL, NULL),
('Брюква', 'Rutabaga', 0, 37, NULL, NULL),
('Бублики', 'Bubliki', 0, 280, NULL, NULL),
('Буженина', 'Buzhenina', 0, 230, NULL, NULL),
('Булгур вареный', 'Boiled bulgur', 0, 83, NULL, NULL),
('Булочка сдобная', 'Sweet bun', 0, 339, NULL, NULL),
('Бульон говяжий', 'Beef broth', 1, 15, NULL, NULL),
('Бульон грибной', 'Mushroom broth', 1, 15, NULL, NULL),
('Бульон куриный', 'Chicken broth', 1, 15, NULL, NULL),
('Бульон овощной', 'Vegetable broth', 1, 10, NULL, NULL),
('Бульон фо', 'Pho broth', 1, 15, 300, NULL),
('Бульонный кубик', 'Bouillon cube', 0, 200, NULL, NULL),
('Бульонный кубик говяжий', 'Beef bouillon cube', 0, 200, NULL, NULL),
('Бульонный кубик куриный', 'Chicken bouillon cube', 0, 200, NULL, NULL),
('Бун бо Хюэ', 'Bun bo Hue', 0, 90, NULL, NULL),
('Бун с говядиной', 'Bun with beef', 0, 110, NULL, NULL),
('Бун с креветками', 'Bun with shrimp', 0, 100, NULL, NULL),
('Бун ча', 'Bun cha', 0, 120, NULL, NULL),
('Вакаме', 'Wakame', 0, 45, NULL, NULL),
('Ванилин', 'Vanillin', 0, 0, NULL, NULL),
('Ваниль стручок', 'Vanilla bean', 0, 288, NULL, NULL),
('Ванильный экстракт', 'Vanilla extract', 0, 288, NULL, NULL),
('Варенец', 'Varenets', 1, 60, NULL, NULL),
('Вареники с вишней', 'Dumplings with cherry', 0, 180, NULL, NULL),
('Вареники с капустой', 'Dumplings with cabbage', 0, 170, NULL, NULL),
('Вареники с картошкой', 'Potato dumplings', 0, 180, NULL, NULL),
('Вареники с творогом', 'Dumplings with cottage cheese', 0, 190, NULL, NULL),
('Варенье', 'Jam', 0, 250, NULL, NULL),
('Васаби', 'Wasabi', 0, 109, NULL, NULL),
('Васаби корень', 'Wasabi root', 0, 109, NULL, NULL),
('Ватеркресс', 'Watercress', 0, 11, NULL, NULL),
('Вафли', 'Waffles', 0, 425, NULL, NULL),
('Вегета', 'Vegeta seasoning', 0, 150, NULL, NULL),
('Вермишель', 'Vermicelli', 0, 112, NULL, NULL),
('Вермут', 'Vermouth', 1, 140, 50, NULL),
('Весенние роллы жареные', 'Fried spring rolls', 0, 250, NULL, NULL),
('Весенние роллы свежие', 'Fresh spring rolls', 0, 100, NULL, NULL),
('Ветчина', 'Ham', 0, 145, NULL, NULL),
('Вешенки', 'Oyster mushrooms', 0, 33, NULL, NULL),
('Винегрет', 'Vinaigrette salad', 0, 130, NULL, NULL),
('Винегрет классический', 'Classic vinaigrette', 0, 130, NULL, NULL),
('Вино белое полусладкое', 'Semi-sweet white wine', 1, 82, 150, NULL),
('Вино белое сухое', 'Dry white wine', 1, 66, 150, NULL),
('Вино красное полусладкое', 'Semi-sweet red wine', 1, 85, 150, NULL),
('Вино красное сухое', 'Dry red wine', 1, 68, 150, NULL),
('Виноград белый', 'White grapes', 0, 69, NULL, NULL),
('Виноград кишмиш белый', 'White grapes', 0, 40, NULL, NULL),
('Виноград красный', 'Red grapes', 0, 69, NULL, NULL),
('Виноград черный', 'Black grapes', 0, 69, NULL, NULL),
('Виски', 'Whiskey', 1, 250, 50, NULL),
('Вишня', 'Sour cherry', 0, 52, NULL, NULL),
('Вкусвилл Биточек куриный с капустой и картофельным пюре', NULL, 0, 148, 200, NULL),
('Вкусвилл Бифштекс говяжий с яйцом и картофельным пюре', NULL, 0, 233, 371, NULL),
('Вкусвилл Котлета куриная в панировке из сухарей с картофельным пюре', NULL, 0, 238, 240, NULL),
('Вобла', 'Vobla', 0, 88, NULL, NULL),
('Вобла вяленая', 'Dried vobla', 0, 235, NULL, NULL),
('Вода', 'Water', 1, 0, NULL, NULL),
('Вода кипяченая', 'Boiled water', 1, 0, NULL, NULL),
('Водка', 'Vodka', 1, 235, 50, NULL),
('Водяной каштан', 'Water chestnut', 0, 97, NULL, NULL),
('Вок овощной', 'Vegetable stir-fry wok', 0, 90, NULL, NULL),
('Вок с говядиной', 'Beef stir-fry wok', 0, 150, NULL, NULL),
('Вок с креветками', 'Shrimp stir-fry wok', 0, 130, NULL, NULL),
('Вок с курицей', 'Chicken stir-fry wok', 0, 140, NULL, NULL),
('Вонтон суп', 'Wonton soup', 0, 50, NULL, NULL),
('Вонтоны', 'Wontons', 0, 180, NULL, NULL),
('Вяленая рыба', 'Dried fish', 0, 220, NULL, NULL),
('Газировка', 'Soda', 1, 42, 330, NULL),
('Гамбургер', 'Hamburger', 0, 295, NULL, NULL),
('Гарам масала', 'Garam masala', 0, 380, NULL, NULL),
('Гвоздика', 'Cloves', 0, 274, NULL, NULL),
('Глазурь сахарная', 'Sugar icing', 0, 380, NULL, NULL),
('Глинтвейн', 'Mulled wine', 1, 132, NULL, NULL),
('Говядина', 'Beef', 0, 250, NULL, NULL),
('Говядина в устричном соусе', 'Beef in oyster sauce', 0, 150, NULL, NULL),
('Говядина вареная', 'Boiled beef', 0, 254, NULL, NULL),
('Говядина монгольская', 'Mongolian beef', 0, 200, NULL, NULL),
('Говядина с брокколи', 'Beef with broccoli', 0, 140, NULL, NULL),
('Годжи', 'Goji berries', 0, 349, NULL, NULL),
('Гой га', 'Goi ga', 0, 100, NULL, NULL),
('Гой ду ду', 'Goi du du', 0, 60, NULL, NULL),
('Гой куон', 'Goi cuon', 0, 90, NULL, NULL),
('Голубика', 'Blueberry', 0, 57, NULL, NULL),
('Голубика сушеная', 'Dried blueberries', 0, 317, NULL, NULL),
('Голубцы', 'Stuffed cabbage', 0, 147, NULL, NULL),
('Горбуша', 'Pink salmon', 0, 140, NULL, NULL),
('Горбуша горячего копчения', 'Hot-smoked pink salmon', 0, 160, NULL, NULL),
('Горбуша жареная', 'Fried pink salmon', 0, 170, NULL, NULL),
('Горбуша запеченная', 'Baked pink salmon', 0, 145, NULL, NULL),
('Горбуша консервированная', 'Canned pink salmon', 0, 136, NULL, NULL),
('Горбуша копченая', 'Smoked pink salmon', 0, 155, NULL, NULL),
('Горбуша слабосоленая', 'Lightly salted pink salmon', 0, 150, NULL, NULL),
('Горбуша соленая', 'Salted pink salmon', 0, 160, NULL, NULL),
('Горбуша холодного копчения', 'Cold-smoked pink salmon', 0, 150, NULL, NULL),
('Горох зеленый', 'Green peas', 0, 81, NULL, NULL),
('Горох сахарный', 'Sugar snap peas', 0, 42, NULL, NULL),
('Гороховая каша', 'Pea porridge', 0, 105, NULL, NULL),
('Гороховый суп', 'Pea soup', 0, 66, NULL, NULL),
('Горошек', 'Peas', 0, 50, NULL, NULL),
('Горчица', 'Mustard', 0, 162, NULL, NULL),
('Горячий шоколад', 'Hot chocolate', 1, 89, 200, NULL),
('Гранадилла', 'Granadilla', 0, 97, NULL, NULL),
('Гранат', 'Pomegranate', 0, 83, NULL, NULL),
('Граппа', 'Grappa', 1, 200, 40, NULL),
('Грейпфрут', 'Grapefruit', 0, 42, NULL, NULL),
('Гренки', 'Croutons', 0, 380, NULL, NULL),
('Греческий салат', 'Greek salad', 0, 128, NULL, NULL),
('Гречка вареная', 'Boiled buckwheat', 0, 88, NULL, NULL),
('Гречка сухая', 'Dry buckwheat', 0, 343, NULL, NULL),
('Грибная приправа', 'Mushroom seasoning', 0, 220, NULL, NULL),
('Грибы жареные', 'Fried mushrooms', 0, 80, NULL, NULL),
('Грибы маринованные', 'Pickled mushrooms', 0, 25, NULL, NULL),
('Грибы соленые', 'Salted mushrooms', 0, 25, NULL, NULL),
('Грибы шиитаке жареные', 'Stir-fried shiitake', 0, 80, NULL, NULL),
('Груша', 'Pear', 0, 57, NULL, NULL),
('Груша дюшес', 'Duchess pear', 0, 57, NULL, NULL),
('Груша конференция', 'Conference pear', 0, 57, NULL, NULL),
('Гуава', 'Guava', 0, 68, NULL, NULL),
('Гуава белая', 'White guava', 0, 68, NULL, NULL),
('Гуава розовая', 'Pink guava', 0, 68, NULL, NULL),
('Гуакамоле', 'Guacamole', 0, 150, NULL, NULL),
('Гуляш', 'Goulash', 0, 140, NULL, NULL),
('Гункан', 'Gunkan', 0, 160, NULL, NULL),
('Гункан с икрой', 'Roe gunkan', 0, 170, NULL, NULL),
('Гункан с тобико', 'Tobiko gunkan', 0, 160, NULL, NULL),
('Гункан с чукой', 'Chuka gunkan', 0, 140, NULL, NULL),
('Гёдза', 'Gyoza', 0, 200, NULL, NULL),
('Дайкири', 'Daiquiri', 1, 125, 120, NULL),
('Дайкон', 'Daikon', 0, 18, NULL, NULL),
('Десерт из бобов', 'Vietnamese bean dessert', 0, 130, NULL, NULL),
('Джамболан', 'Java plum', 0, 60, NULL, NULL),
('Джекфрут', 'Jackfruit', 0, 95, NULL, NULL),
('Джин', 'Gin', 1, 263, 50, NULL),
('Дим сам', 'Dim sum', 0, 180, NULL, NULL),
('Донер', 'Doner', 0, 220, NULL, NULL),
('Дорадо', 'Dorado', 0, 96, NULL, NULL),
('Дорадо запеченный', 'Baked dorado', 0, 110, NULL, NULL),
('Дорадо на гриле', 'Grilled dorado', 0, 120, NULL, NULL),
('Драконий фрукт', 'Dragon fruit', 0, 60, NULL, NULL),
('Драники', 'Potato pancakes', 0, 220, NULL, NULL),
('Дрожжи', 'Yeast', 0, 325, NULL, NULL),
('Дрожжи быстродействующие', 'Instant yeast', 0, 325, NULL, NULL),
('Дрожжи прессованные', 'Compressed yeast', 0, 109, NULL, NULL),
('Дрожжи свежие', 'Fresh yeast', 0, 109, NULL, NULL),
('Дрожжи сухие', 'Dry yeast', 0, 325, NULL, NULL),
('Дуриан', 'Durian', 0, 147, NULL, NULL),
('Дыня', 'Melon', 0, 34, NULL, NULL),
('Дыня Колхозница', 'Kolkhoznitsa melon', 0, 39, NULL, NULL),
('Дыня Торпеда', 'Torpedo melon', 0, 34, NULL, NULL),
('Ежевика', 'Blackberry', 0, 43, NULL, NULL),
('Жаркое с курицей', 'Chicken stew', 0, 113, NULL, NULL),
('Жевательная резинка', 'Chewing gum', 0, 250, NULL, NULL),
('Желатин', 'Gelatin', 0, 355, NULL, NULL),
('Желатин пищевой', 'Food gelatin', 0, 355, NULL, NULL),
('Жимолость', 'Honeysuckle', 0, 30, NULL, NULL),
('Заатар', 'Zaatar', 0, 300, NULL, NULL),
('Заливное из рыбы', 'Fish aspic', 0, 80, NULL, NULL),
('Земляника', 'Wild strawberry', 0, 41, NULL, NULL),
('Зефир', 'Marshmallow zefir', 0, 326, NULL, NULL),
('Зефир в шоколаде', 'Chocolate marshmallow', 0, 396, 30, NULL),
('Зира', 'Cumin', 0, 375, NULL, NULL),
('Изюм', 'Raisins', 0, 264, NULL, NULL),
('Изюм для выпечки', 'Raisins for baking', 0, 264, NULL, NULL),
('Изюм кишмиш', 'Sultanas', 0, 282, NULL, NULL),
('Изюм кишмиш для выпечки', 'Sultanas for baking', 0, 282, NULL, NULL),
('Икра баклажанная', 'Eggplant caviar', 0, 90, NULL, NULL),
('Икра горбуши', 'Pink salmon caviar', 0, 230, NULL, NULL),
('Икра кеты', 'Chum salmon caviar', 0, 249, NULL, NULL),
('Икра красная', 'Red caviar', 0, 249, NULL, NULL),
('Икра летучей рыбы', 'Tobiko', 0, 120, NULL, NULL),
('Икра лососевая', 'Salmon caviar', 0, 249, NULL, NULL),
('Икра масаго', 'Masago', 0, 110, NULL, NULL),
('Икра мойвы', 'Capelin roe', 0, 130, NULL, NULL),
('Икра мойвы в соусе', 'Capelin roe in sauce', 0, 200, NULL, NULL),
('Икра нерки', 'Sockeye caviar', 0, 250, NULL, NULL),
('Икра судака', 'Zander caviar', 0, 120, NULL, NULL),
('Икра трески', 'Cod roe', 0, 115, NULL, NULL),
('Икра черная', 'Black caviar', 0, 235, NULL, NULL),
('Икра щуки', 'Pike caviar', 0, 130, NULL, NULL),
('Имбирь', 'Ginger', 0, 80, NULL, NULL),
('Имбирь маринованный', 'Pickled ginger', 0, 50, NULL, NULL),
('Имбирь молотый', 'Ground ginger', 0, 335, NULL, NULL),
('Имеретинский шафран', 'Imeretian saffron', 0, 250, NULL, NULL),
('Индейка вареная', 'Boiled turkey', 0, 130, NULL, NULL),
('Инжир', 'Fig', 0, 74, NULL, NULL),
('Инжир сушеный', 'Dried figs', 0, 249, NULL, NULL),
('Ирга', 'Serviceberry', 0, 45, NULL, NULL),
('Ирис', 'Toffee', 0, 420, NULL, NULL),
('Ирландский кофе', 'Irish coffee', 1, 110, 200, NULL),
('Итальянские травы', 'Italian herbs', 0, 250, NULL, NULL),
('Йогурт греческий', 'Greek yogurt', 0, 97, NULL, NULL),
('Йогурт натуральный', 'Natural yogurt', 1, 66, NULL, NULL),
('Йогурт питьевой', 'Drinking yogurt', 1, 75, 250, NULL),
('Кабачковая икра', 'Zucchini caviar', 0, 97, NULL, NULL),
('Кабачок', 'Zucchini', 0, 24, NULL, NULL),
('Кабачок спагетти', 'Spaghetti squash', 0, 31, NULL, NULL),
('Кабачок фаршированный', 'Stuffed zucchini', 0, 90, NULL, NULL),
('Кабачок цуккини', 'Zucchini', 0, 17, NULL, NULL),
('Кагор', 'Cahors wine', 1, 163, 100, NULL),
('Кайенский перец молотый', 'Ground cayenne', 0, 318, NULL, NULL),
('Какао на воде', 'Cocoa with water', 1, 35, 200, NULL),
('Какао порошок', 'Cocoa powder', 0, 228, NULL, NULL),
('Какао с молоком', 'Cocoa with milk', 1, 89, NULL, NULL),
('Какао щелоченное', 'Dutch cocoa', 0, 228, NULL, NULL),
('Кактус нопаль', 'Nopal cactus', 0, 16, NULL, NULL),
('Кактус плод', 'Prickly pear', 0, 41, NULL, NULL),
('Кале', 'Kale', 0, 49, NULL, NULL),
('Калина', 'Viburnum', 0, 26, NULL, NULL),
('Калуа', 'Kahlua', 1, 270, 40, NULL),
('Кальвадос', 'Calvados', 1, 240, 50, NULL),
('Кальмары', 'Squid', 0, 100, NULL, NULL),
('Кальмары жареные вьетнамские', 'Vietnamese fried squid', 0, 160, NULL, NULL),
('Кальмары по-сычуаньски', 'Sichuan squid', 0, 140, NULL, NULL),
('Камбала', 'Flounder', 0, 83, NULL, NULL),
('Камбала жареная', 'Fried flounder', 0, 150, NULL, NULL),
('Камбала запеченная', 'Baked flounder', 0, 100, NULL, NULL),
('Као лау', 'Cao lau', 0, 130, NULL, NULL),
('Капрезе', 'Caprese', 0, 150, NULL, NULL),
('Капуста', 'Cabbage', 0, 25, NULL, NULL),
('Капуста брюссельская', 'Brussels sprouts', 0, 43, NULL, NULL),
('Капуста краснокочанная', 'Red cabbage', 0, 31, NULL, NULL),
('Капуста пекинская', 'Napa cabbage', 0, 16, NULL, NULL),
('Капуста савойская', 'Savoy cabbage', 0, 27, NULL, NULL),
('Капуста тушеная', 'Stewed cabbage', 0, 75, NULL, NULL),
('Капучино с сахаром', 'Cappuccino with sugar', 1, 60, 200, NULL),
('Карамбола', 'Starfruit', 0, 31, NULL, NULL),
('Карамбола сладкая', 'Sweet starfruit', 0, 31, NULL, NULL),
('Карась', 'Crucian carp', 0, 87, NULL, NULL),
('Карась жареный', 'Fried crucian carp', 0, 150, NULL, NULL),
('Кардамон', 'Cardamom', 0, 311, NULL, NULL),
('Карп', 'Carp', 0, 112, NULL, NULL),
('Карп жареный', 'Fried carp', 0, 160, NULL, NULL),
('Карп запеченный', 'Baked carp', 0, 130, NULL, NULL),
('Карп фаршированный', 'Stuffed carp', 0, 140, NULL, NULL),
('Карри вьетнамский с говядиной', 'Vietnamese beef curry', 0, 150, NULL, NULL),
('Карри вьетнамский с курицей', 'Vietnamese chicken curry', 0, 140, NULL, NULL),
('Карри порошок', 'Curry powder', 0, 325, NULL, NULL),
('Картофель фри', 'French fries', 0, 312, NULL, NULL),
('Картофельное пюре', 'Mashed potatoes', 0, 88, NULL, NULL),
('Картошка', 'Potatoes', 0, 77, NULL, NULL),
('Картошка вареная', 'Boiled potatoes', 0, 82, NULL, NULL),
('Картошка жареная', 'Fried potatoes', 0, 192, NULL, NULL),
('Картошка запеченная', 'Baked potatoes', 0, 93, NULL, NULL),
('Картошка фри', 'French fries', 0, 312, NULL, NULL),
('Каша гречневая с молоком', 'Buckwheat porridge with milk', 0, 100, NULL, NULL),
('Каша овсяная с молоком', 'Oatmeal with milk', 0, 100, NULL, NULL),
('Каша пшенная с молоком', 'Millet porridge with milk', 0, 105, NULL, NULL),
('Каша рисовая вьетнамская', 'Vietnamese rice porridge', 0, 55, NULL, NULL),
('Каша рисовая с молоком', 'Rice porridge with milk', 0, 110, NULL, NULL),
('Квас', 'Kvass', 1, 27, NULL, NULL),
('Квашеная капуста', 'Sauerkraut', 0, 19, NULL, NULL),
('Квашеная капуста с маслом', 'Sauerkraut with oil', 0, 50, NULL, NULL),
('Квашеные огурцы', 'Fermented cucumbers', 0, 11, NULL, NULL),
('Кета', 'Chum salmon', 0, 127, NULL, NULL),
('Кета копченая', 'Smoked chum salmon', 0, 145, NULL, NULL),
('Кета слабосоленая', 'Lightly salted chum salmon', 0, 140, NULL, NULL),
('Кета соленая', 'Salted chum salmon', 0, 150, NULL, NULL),
('Кетчуп', NULL, 0, 112, NULL, NULL),
('Кефир 1%', 'Kefir 1%', 1, 40, NULL, NULL),
('Кефир 2,5%', 'Kefir 2.5%', 1, 50, NULL, NULL),
('Кефир 3,2%', 'Kefir 3.2%', 1, 56, NULL, NULL),
('Киви', 'Kiwi', 0, 61, NULL, NULL),
('Кижуч', 'Coho salmon', 0, 140, NULL, NULL),
('Кижуч копченый', 'Smoked coho', 0, 155, NULL, NULL),
('Кижуч слабосоленый', 'Lightly salted coho', 0, 150, NULL, NULL),
('Кизил', 'Cornelian cherry', 0, 44, NULL, NULL),
('Килька', 'Sprat kilka', 0, 137, NULL, NULL),
('Килька в томате', 'Kilka in tomato sauce', 0, 140, NULL, NULL),
('Килька копченая', 'Smoked kilka', 0, 180, NULL, NULL),
('Килька соленая', 'Salted kilka', 0, 150, NULL, NULL),
('Кимчи', 'Kimchi', 0, 15, NULL, NULL),
('Кинза', NULL, 0, 23, NULL, NULL),
('Киноа вареная', 'Boiled quinoa', 0, 120, NULL, NULL),
('Кисель', 'Kissel', 1, 53, 200, NULL),
('КитКат', 'KitKat', 0, 518, 45, NULL),
('Клементин', 'Clementine', 0, 47, NULL, NULL),
('Клубника', 'Strawberry', 0, 33, NULL, NULL),
('Клубника садовая', 'Garden strawberry', 0, 33, NULL, NULL),
('Клюква', 'Cranberry', 0, 46, NULL, NULL),
('Клюква сушеная', 'Dried cranberries', 0, 308, NULL, NULL),
('Козинак', 'Kozinak', 0, 510, NULL, NULL),
('Кокос молодой', 'Young coconut', 0, 60, NULL, NULL),
('Кокос мякоть', 'Coconut meat', 0, 354, NULL, NULL),
('Кокосовая вода', 'Coconut water', 1, 19, NULL, NULL),
('Кокосовая стружка', 'Coconut flakes', 0, 660, NULL, NULL),
('Кокосовая стружка для выпечки', 'Coconut flakes for baking', 0, 660, NULL, NULL),
('Кокосовое молоко', 'Coconut milk', 1, 180, NULL, NULL),
('Кола', 'Cola', 1, 42, 330, NULL),
('Кола Добрый', NULL, 1, 0.3, NULL, NULL),
('Колбаса вареная', 'Boiled sausage', 0, 250, NULL, NULL),
('Колбаса докторская', 'Doctor''s sausage', 0, 257, NULL, NULL),
('Колбаса сырокопченая', 'Cured sausage', 0, 460, NULL, NULL),
('Кольраби', 'Kohlrabi', 0, 27, NULL, NULL),
('Ком га', 'Com ga', 0, 150, NULL, NULL),
('Ком там', 'Com tam', 0, 160, NULL, NULL),
('Компот', 'Kompot', 1, 60, NULL, NULL),
('Конджи', 'Congee', 0, 50, NULL, NULL),
('Консервы рыбные', 'Canned fish', 0, 150, NULL, NULL),
('Коньяк', 'Cognac', 1, 239, 50, NULL),
('Копченая соль', 'Smoked salt', 0, 0, NULL, NULL),
('Корень сельдерея', 'Celeriac', 0, 42, NULL, NULL),
('Кориандр молотый', 'Ground coriander', 0, 298, NULL, NULL),
('Кориандр семена', 'Coriander seeds', 0, 298, NULL, NULL),
('Корица молотая', 'Ground cinnamon', 0, 247, NULL, NULL),
('Корица палочки', 'Cinnamon sticks', 0, 247, NULL, NULL),
('Корн', 'Lamb''s lettuce', 0, 21, NULL, NULL),
('Корюшка', 'Smelt', 0, 102, NULL, NULL),
('Корюшка жареная', 'Fried smelt', 0, 180, NULL, NULL),
('Космополитен', 'Cosmopolitan', 1, 130, 100, NULL),
('Котлета говяжья', 'Beef cutlet', 0, 250, NULL, NULL),
('Котлета куриная', 'Chicken cutlet', 0, 220, NULL, NULL),
('Котлета по-киевски', 'Chicken Kiev', 0, 290, NULL, NULL),
('Котлеты из минтая', 'Pollock cutlets', 0, 160, NULL, NULL),
('Котлеты из щуки', 'Pike cutlets', 0, 150, NULL, NULL),
('Коул слоу', 'Coleslaw', 0, 120, NULL, NULL),
('Кофе Капучино без сахара', 'Cappuccino no sugar', 1, 53, NULL, NULL),
('Кофе Латте', 'Latte', 1, 44, NULL, NULL),
('Кофе Флэт Уайт', 'Flat White', 1, 42, 200, NULL),
('Кофе вьетнамский', 'Vietnamese coffee', 1, 60, 200, NULL),
('Кофе капучино домашнее', NULL, 1, 67, 290, NULL),
('Кофе сгущенка вьетнамский', 'Vietnamese iced coffee', 1, 90, 250, NULL),
('Кофе черный без сахара', 'Black coffee no sugar', 1, 2, NULL, NULL),
('Краб', 'Crab', 0, 97, NULL, NULL),
('Красная смородина', 'Red currant', 0, 39, NULL, NULL),
('Крахмал', 'Starch', 0, 330, NULL, NULL),
('Крахмал картофельный', 'Potato starch', 0, 313, NULL, NULL),
('Крахмал кукурузный', 'Corn starch', 0, 343, NULL, NULL),
('Крахмал тапиоковый', 'Tapioca starch', 0, 358, NULL, NULL),
('Креветки', 'Shrimp', 0, 95, NULL, NULL),
('Креветки в кляре', 'Battered shrimp', 0, 220, NULL, NULL),
('Креветки в рыбном соусе', 'Shrimp in fish sauce', 0, 130, NULL, NULL),
('Креветки кунг пао', 'Kung Pao shrimp', 0, 160, NULL, NULL),
('Креветки на гриле вьетнамские', 'Vietnamese grilled shrimp', 0, 120, NULL, NULL),
('Крекеры', 'Crackers', 0, 450, NULL, NULL),
('Кресс-салат', 'Garden cress', 0, 32, NULL, NULL),
('Кролик', 'Rabbit', 0, 173, NULL, NULL),
('Круассан', 'Croissant', 0, 406, NULL, NULL),
('Крыжовник', 'Gooseberry', 0, 44, NULL, NULL),
('Крылышки куриные', 'Chicken wings', 0, 203, NULL, NULL),
('Кукуруза', 'Corn', 0, 86, NULL, NULL),
('Кукуруза мини', 'Baby corn', 0, 26, NULL, NULL),
('Кукуруза сахарная', 'Sweet corn', 0, 86, NULL, NULL),
('Кукурузная каша', 'Corn porridge', 0, 86, NULL, NULL),
('Кумин', 'Cumin', 0, 375, NULL, NULL),
('Кумкват', 'Kumquat', 0, 71, NULL, NULL),
('Кунжут', 'Sesame', 0, 565, NULL, NULL),
('Кунжутное масло китайское', 'Chinese sesame oil', 0, 884, NULL, NULL),
('Кунжутные шарики', 'Sesame balls', 0, 350, NULL, NULL),
('Курага', 'Dried apricots', 0, 215, NULL, NULL),
('Курага турецкая', 'Turkish dried apricots', 0, 215, NULL, NULL),
('Куриная грудка вареная', NULL, 0, 165, NULL, NULL),
('Куриный суп', 'Chicken soup', 0, 36, NULL, NULL),
('Курица апельсиновая', 'Orange chicken', 0, 230, NULL, NULL),
('Курица в кисло-сладком соусе', 'Sweet and sour chicken', 0, 200, NULL, NULL),
('Курица вареная', 'Boiled chicken', 0, 170, NULL, NULL),
('Курица генерала Цо', 'General Tso''s chicken', 0, 250, NULL, NULL),
('Курица гриль', 'Grilled chicken', 0, 184, NULL, NULL),
('Курица кунг пао', 'Kung Pao chicken', 0, 180, NULL, NULL),
('Курица на гриле вьетнамская', 'Vietnamese grilled chicken', 0, 180, NULL, NULL),
('Курица с кешью', 'Cashew chicken', 0, 190, NULL, NULL),
('Курица терияки', 'Teriyaki chicken', 0, 170, NULL, NULL),
('Курица филе', 'Chicken breast', 0, 110, NULL, NULL),
('Куркума', 'Turmeric', 0, 312, NULL, NULL),
('Куркума молотая', 'Ground turmeric', 0, 312, NULL, NULL),
('Кускус вареный', 'Boiled couscous', 0, 112, NULL, NULL),
('Кусок пиццы', 'Pizza slice', 0, 270, NULL, NULL),
('Лаваш', 'Lavash', 0, 275, NULL, NULL),
('Лавровый лист', 'Bay leaf', 0, 313, NULL, NULL),
('Лагман', 'Lagman', 0, 110, NULL, NULL),
('Лазанья', 'Lasagna', 0, 160, NULL, NULL),
('Лайм', 'Lime', 0, 30, NULL, NULL),
('Лапша быстрого приготовления', 'Instant noodles', 0, 450, NULL, NULL),
('Лапша даньдань', 'Dan dan noodles', 0, 160, NULL, NULL),
('Лапша ло мейн', 'Lo mein', 0, 130, NULL, NULL),
('Лапша рисовая', 'Rice noodles', 0, 110, NULL, NULL),
('Лапша рисовая вьетнамская', 'Vietnamese rice noodles', 0, 110, NULL, NULL),
('Лапша с говядиной китайская', 'Chinese beef noodles', 0, 120, NULL, NULL),
('Лапша стеклянная', 'Glass noodles', 0, 100, NULL, NULL),
('Лапша чжацзянмянь', 'Zhajiangmian', 0, 150, NULL, NULL),
('Лапша чоу мейн', 'Chow mein', 0, 140, NULL, NULL),
('Лапша яичная', 'Egg noodles', 0, 138, NULL, NULL),
('Леденцы', 'Hard candy', 0, 380, NULL, NULL),
('Лечо', 'Lecho', 0, 70, NULL, NULL),
('Лещ', 'Bream', 0, 105, NULL, NULL),
('Лещ вяленый', 'Dried bream', 0, 220, NULL, NULL),
('Лещ запеченный', 'Baked bream', 0, 120, NULL, NULL),
('Лещ копченый', 'Smoked bream', 0, 150, NULL, NULL),
('Ликер', 'Liqueur', 1, 270, 40, NULL),
('Лимон', 'Lemon', 0, 29, NULL, NULL),
('Лимонад', 'Lemonade', 1, 40, 250, NULL),
('Лимонад вьетнамский', 'Vietnamese lemonade', 1, 40, 300, NULL),
('Лимонная кислота', 'Citric acid', 0, 0, NULL, NULL),
('Лимонная цедра', 'Lemon zest', 0, 47, NULL, NULL),
('Лисички', 'Chanterelles', 0, 19, NULL, NULL),
('Личи', 'Lychee', 0, 66, NULL, NULL),
('Лолло россо', 'Lollo rosso', 0, 15, NULL, NULL),
('Лонган', 'Longan', 0, 60, NULL, NULL),
('Лосось', 'Salmon', 0, 208, NULL, NULL),
('Лосось горячего копчения', 'Hot-smoked salmon', 0, 190, NULL, NULL),
('Лосось гриль', 'Grilled salmon', 0, 190, NULL, NULL),
('Лосось жареный', 'Fried salmon', 0, 220, NULL, NULL),
('Лосось запеченный', 'Baked salmon', 0, 180, NULL, NULL),
('Лосось копченый', 'Smoked salmon', 0, 180, NULL, NULL),
('Лосось на пару', 'Steamed salmon', 0, 170, NULL, NULL),
('Лосось слабосоленый', 'Lightly salted salmon', 0, 202, NULL, NULL),
('Лосось соленый', 'Salted salmon', 0, 210, NULL, NULL),
('Лосось стейк', 'Salmon steak', 0, 208, NULL, NULL),
('Лосось сырой', 'Raw salmon', 0, 208, NULL, NULL),
('Лосось филе', 'Salmon fillet', 0, 208, NULL, NULL),
('Лосось холодного копчения', 'Cold-smoked salmon', 0, 170, NULL, NULL),
('Лотос корень', 'Lotus root', 0, 74, NULL, NULL),
('Лук жареный', 'Fried onion', 0, 180, NULL, NULL),
('Лук зеленый', 'Green onion', 0, 19, NULL, NULL),
('Лук красный', 'Red onion', 0, 40, NULL, NULL),
('Лук порошок', 'Onion powder', 0, 349, NULL, NULL),
('Лук репчатый', 'Onion', 0, 40, NULL, NULL),
('Лук сушеный', 'Dried onion', 0, 349, NULL, NULL),
('Лук шалот', 'Shallot', 0, 72, NULL, NULL),
('Лук-порей', 'Leek', 0, 61, NULL, NULL),
('Лунный пирог', 'Mooncake', 0, 420, NULL, NULL),
('Люля-кебаб', 'Lyulya kebab', 0, 240, NULL, NULL),
('М&M''s', 'M&M''s', 0, 492, NULL, NULL),
('Мадера', 'Madeira', 1, 160, 50, NULL),
('Майонез', NULL, 0, 620, NULL, NULL),
('Майоран', 'Marjoram', 0, 271, NULL, NULL),
('Мак пищевой', 'Poppy seeds', 0, 525, NULL, NULL),
('Макарон', 'Macaron', 0, 400, NULL, NULL),
('Макароны отварные', 'Boiled pasta', 0, 112, NULL, NULL),
('Маки с авокадо', 'Avocado maki', 0, 140, NULL, NULL),
('Маки с креветкой', 'Shrimp maki', 0, 140, NULL, NULL),
('Маки с лососем', 'Salmon maki', 0, 155, NULL, NULL),
('Маки с огурцом', 'Cucumber maki', 0, 115, NULL, NULL),
('Маки с тунцом', 'Tuna maki', 0, 145, NULL, NULL),
('Маки с угрем', 'Eel maki', 0, 185, NULL, NULL),
('Малина', 'Raspberry', 0, 53, NULL, NULL),
('Манго', 'Mango', 0, 70, NULL, NULL),
('Манго зеленый', 'Green mango', 0, 60, NULL, NULL),
('Манго пудинг', 'Mango pudding', 0, 120, NULL, NULL),
('Мангольд', 'Chard', 0, 19, NULL, NULL),
('Мангостин', 'Mangosteen', 0, 73, NULL, NULL),
('Мандарин', 'Mandarin', 0, 53, NULL, NULL),
('Мандарин уншиу', 'Satsuma mandarin', 0, 42, NULL, NULL),
('Маниок', 'Cassava', 0, 160, NULL, NULL),
('Манная каша', 'Semolina porridge', 0, 98, NULL, NULL),
('Манты', 'Manty', 0, 220, NULL, NULL),
('Мапо тофу', 'Mapo tofu', 0, 120, NULL, NULL),
('Маракуйя', 'Passion fruit', 0, 97, NULL, NULL),
('Маракуйя желтая', 'Yellow passion fruit', 0, 97, NULL, NULL),
('Маргарин', 'Margarine', 0, 743, NULL, NULL),
('Маргарита', 'Margarita', 1, 125, 150, NULL),
('Маринованные огурцы', 'Pickled cucumbers', 0, 16, NULL, NULL),
('Маринованные помидоры', 'Pickled tomatoes', 0, 32, NULL, NULL),
('Мармелад', 'Marmalade', 0, 300, NULL, NULL),
('Марс', 'Mars bar', 0, 450, 50, NULL),
('Мартини', 'Martini', 1, 140, 100, NULL),
('Марципан', 'Marzipan', 0, 470, NULL, NULL),
('Маслины', 'Black olives', 0, 115, NULL, NULL),
('Масло авокадо', 'Avocado oil', 0, 884, NULL, NULL),
('Масло виноградных косточек', 'Grape seed oil', 0, 884, NULL, NULL),
('Масло икорное', 'Caviar butter', 0, 400, NULL, NULL),
('Масло кокосовое', 'Coconut oil', 0, 899, NULL, NULL),
('Масло кукурузное', 'Corn oil', 0, 899, NULL, NULL),
('Масло кунжутное', 'Sesame oil', 0, 884, NULL, NULL),
('Масло льняное', 'Linseed oil', 0, 898, NULL, NULL),
('Масло оливковое', 'Olive oil', 0, 884, NULL, NULL),
('Масло подсолнечное', 'Sunflower oil', 0, 899, NULL, NULL),
('Масло сливочное', 'Butter', 0, 750, NULL, NULL),
('Масло топленое', 'Ghee', 0, 885, NULL, NULL),
('Мастика сахарная', 'Sugar fondant', 0, 380, NULL, NULL),
('Матча латте', 'Matcha latte', 1, 55, 250, NULL),
('Мед', 'Honey', 0, 329, NULL, NULL),
('Медовуха', 'Mead', 1, 70, 200, NULL),
('Ми Куанг', 'Mi Quang', 0, 140, NULL, NULL),
('Мидии', 'Mussels', 0, 77, NULL, NULL),
('Мизуна', 'Mizuna', 0, 21, NULL, NULL),
('Микрозелень', 'Microgreens', 0, 30, NULL, NULL),
('Миндальное молоко', 'Almond milk', 1, 25, NULL, NULL),
('Минеола', 'Minneola', 0, 47, NULL, NULL),
('Минеральная вода', 'Mineral water', 1, 0, 500, NULL),
('Мини-киви', 'Baby kiwi', 0, 61, NULL, NULL),
('Минтай', 'Pollock', 0, 72, NULL, NULL),
('Минтай в кляре', 'Battered pollock', 0, 180, NULL, NULL),
('Минтай вареный', 'Boiled pollock', 0, 72, NULL, NULL),
('Минтай жареный', 'Fried pollock', 0, 140, NULL, NULL),
('Минтай запеченный', 'Baked pollock', 0, 90, NULL, NULL),
('Минтай на пару', 'Steamed pollock', 0, 75, NULL, NULL),
('Мисо суп', 'Miso soup', 0, 35, NULL, NULL),
('Мойва', 'Capelin', 0, 157, NULL, NULL),
('Мойва жареная', 'Fried capelin', 0, 220, NULL, NULL),
('Мойва копченая', 'Smoked capelin', 0, 180, NULL, NULL),
('Молоко 0,5%', 'Milk 0.5%', 1, 35, NULL, NULL),
('Молоко 1,5%', 'Milk 1.5%', 1, 44, NULL, NULL),
('Молоко 2,5%', 'Milk 2.5%', 1, 52, NULL, NULL),
('Молоко 3.2 %', NULL, 1, 62, NULL, NULL),
('Молоко 6%', 'Milk 6%', 1, 84, NULL, NULL),
('Молоко безлактозное', NULL, 1, 47, NULL, NULL),
('Молоко топленое', 'Baked milk', 1, 67, NULL, NULL),
('Морковь', 'Carrot', 0, 32, NULL, NULL),
('Морковь вареная', 'Boiled carrot', 0, 35, NULL, NULL),
('Мороженое пломбир', 'Ice cream plombir', 0, 227, NULL, NULL),
('Морс', 'Fruit drink', 1, 52, NULL, NULL),
('Морская капуста', 'Seaweed kelp', 0, 49, NULL, NULL),
('Мохито', 'Mojito', 1, 71, 250, NULL),
('Мука блинная', 'Pancake flour', 0, 340, NULL, NULL),
('Мука гречневая', 'Buckwheat flour', 0, 335, NULL, NULL),
('Мука для блинов', 'Pancake mix flour', 0, 350, NULL, NULL),
('Мука из твердых сортов пшеницы', 'Durum flour', 0, 350, NULL, NULL),
('Мука кокосовая', 'Coconut flour', 0, 400, NULL, NULL),
('Мука кондитерская', 'Pastry flour', 0, 360, NULL, NULL),
('Мука кукурузная', 'Corn flour', 0, 331, NULL, NULL),
('Мука льняная', 'Flax flour', 0, 270, NULL, NULL),
('Мука миндальная', 'Almond flour', 0, 575, NULL, NULL),
('Мука нутовая', 'Chickpea flour', 0, 387, NULL, NULL),
('Мука овсяная', 'Oat flour', 0, 369, NULL, NULL),
('Мука полбяная', 'Spelt flour', 0, 338, NULL, NULL),
('Мука пшеничная', 'Wheat flour', 0, 364, NULL, NULL),
('Мука пшеничная высший сорт', 'Premium wheat flour', 0, 334, NULL, NULL),
('Мука пшеничная цельнозерновая', 'Whole wheat flour', 0, 340, NULL, NULL),
('Мука ржаная', 'Rye flour', 0, 298, NULL, NULL),
('Мука рисовая', 'Rice flour', 0, 366, NULL, NULL),
('Мускатный орех', 'Nutmeg', 0, 525, NULL, NULL),
('Мускатный орех молотый', 'Ground nutmeg', 0, 525, NULL, NULL),
('Мюсли', 'Muesli', 0, 352, NULL, NULL),
('Мюсли батончик', 'Muesli bar', 0, 380, NULL, NULL),
('Мята свежая', 'Fresh mint', 0, 70, NULL, NULL),
('Мята сушеная', 'Dried mint', 0, 285, NULL, NULL),
('Навага', 'Navaga', 0, 73, NULL, NULL),
('Навага жареная', 'Fried navaga', 0, 140, NULL, NULL),
('Наггетсы', 'Nuggets', 0, 296, NULL, NULL),
('Наггетсы куриные', 'Chicken nuggets', 0, 296, NULL, NULL),
('Настойка', 'Tincture', 1, 220, 50, NULL),
('Нектарин', 'Nectarine', 0, 44, NULL, NULL),
('Нектарин белый', 'White nectarine', 0, 44, NULL, NULL),
('Нем куон', 'Nem cuon', 0, 100, NULL, NULL),
('Нем ран', 'Nem ran', 0, 250, NULL, NULL),
('Нерка', 'Sockeye salmon', 0, 157, NULL, NULL),
('Нерка консервированная', 'Canned sockeye', 0, 153, NULL, NULL),
('Нерка копченая', 'Smoked sockeye', 0, 170, NULL, NULL),
('Нерка слабосоленая', 'Lightly salted sockeye', 0, 165, NULL, NULL),
('Несквик', 'Nesquik', 0, 379, NULL, NULL),
('Нигири', 'Nigiri', 0, 150, NULL, NULL),
('Нигири с креветкой', 'Shrimp nigiri', 0, 140, NULL, NULL),
('Нигири с лососем', 'Salmon nigiri', 0, 160, NULL, NULL),
('Нигири с тунцом', 'Tuna nigiri', 0, 150, NULL, NULL),
('Нигири с угрем', 'Eel nigiri', 0, 200, NULL, NULL),
('Нони', 'Noni', 0, 44, NULL, NULL),
('Нори', 'Nori', 0, 35, NULL, NULL),
('Нуга', 'Nougat', 0, 400, NULL, NULL),
('Нут вареный', 'Boiled chickpeas', 0, 164, NULL, NULL),
('Нут жареный', 'Roasted chickpeas', 0, 400, NULL, NULL),
('Нутелла', 'Nutella', 0, 539, NULL, NULL),
('Облепиха', 'Sea buckthorn', 0, 82, NULL, NULL),
('Овощи в устричном соусе', 'Vegetables in oyster sauce', 0, 70, NULL, NULL),
('Овощи на гриле', 'Grilled vegetables', 0, 50, NULL, NULL),
('Овощи на пару', 'Steamed vegetables', 0, 35, NULL, NULL),
('Овощное рагу', 'Vegetable stew', 0, 60, NULL, NULL),
('Овсянка', 'Oatmeal', 0, 102, NULL, NULL),
('Овсянка сухая', 'Dry oatmeal', 0, 352, NULL, NULL),
('Овсяное молоко', 'Oat milk', 1, 45, NULL, NULL),
('Огурец армянский', 'Armenian cucumber', 0, 12, NULL, NULL),
('Огурец длинноплодный', 'Long cucumber', 0, 15, NULL, NULL),
('Огурец короткоплодный', 'Short cucumber', 0, 15, NULL, NULL),
('Огурцы', 'Cucumber', 0, 15, NULL, NULL),
('Окорочок гриль', 'Grilled chicken leg', 0, 181, NULL, NULL),
('Окра', 'Okra', 0, 33, NULL, NULL),
('Окрошка', 'Okroshka', 0, 55, NULL, NULL),
('Окрошка на квасе', 'Okroshka with kvass', 0, 55, NULL, NULL),
('Окрошка на кефире', 'Okroshka with kefir', 0, 60, NULL, NULL),
('Окунь', 'Perch', 0, 82, NULL, NULL),
('Окунь жареный', 'Fried perch', 0, 140, NULL, NULL),
('Окунь морской', 'Ocean perch', 0, 103, NULL, NULL),
('Окунь морской жареный', 'Fried ocean perch', 0, 160, NULL, NULL),
('Оладьи', 'Oladyi', 0, 215, NULL, NULL),
('Оладьи со сметаной', 'Oladyi with sour cream', 0, 220, NULL, NULL),
('Оливки', 'Olives', 0, 115, NULL, NULL),
('Омлет', 'Omelette', 0, 154, NULL, NULL),
('Омлет вьетнамский', 'Vietnamese omelette', 0, 160, NULL, NULL),
('Онигири', 'Onigiri', 0, 180, NULL, NULL),
('Онигири с лососем', 'Salmon onigiri', 0, 190, NULL, NULL),
('Онигири с тунцом', 'Tuna onigiri', 0, 185, NULL, NULL),
('Орегано', 'Oregano', 0, 265, NULL, NULL),
('Орегано сушеный', 'Dried oregano', 0, 265, NULL, NULL),
('Орех арахис', 'Peanuts', 0, 567, NULL, NULL),
('Орех бразильский', 'Brazil nuts', 0, 656, NULL, NULL),
('Орех грецкий', 'Walnuts', 0, 654, NULL, NULL),
('Орех кедровый', 'Pine nuts', 0, 680, NULL, NULL),
('Орех кешью', 'Cashew nuts', 0, 553, NULL, NULL),
('Орех макадамия', 'Macadamia nuts', 0, 718, NULL, NULL),
('Орех миндаль', 'Almonds', 0, 649, NULL, NULL),
('Орех пекан', 'Pecan nuts', 0, 691, NULL, NULL),
('Орех фисташки', 'Pistachios', 0, 562, NULL, NULL),
('Орех фундук', 'Hazelnuts', 0, 628, NULL, NULL),
('Орехи грецкие для выпечки', 'Walnuts for baking', 0, 654, NULL, NULL),
('Осётр', 'Sturgeon', 0, 164, NULL, NULL),
('Осётр запеченный', 'Baked sturgeon', 0, 170, NULL, NULL),
('Осётр копченый', 'Smoked sturgeon', 0, 180, NULL, NULL),
('Отбивная свиная', 'Pork chop', 0, 280, NULL, NULL),
('Пак-чой', 'Pak choi', 0, 13, NULL, NULL),
('Палтус', 'Halibut', 0, 103, NULL, NULL),
('Палтус жареный', 'Fried halibut', 0, 160, NULL, NULL),
('Палтус копченый', 'Smoked halibut', 0, 140, NULL, NULL),
('Палтус слабосоленый', 'Lightly salted halibut', 0, 120, NULL, NULL),
('Панировочные сухари', 'Breadcrumbs', 0, 347, NULL, NULL),
('Папайя', 'Papaya', 0, 43, NULL, NULL),
('Папайя зеленая', 'Green papaya', 0, 39, NULL, NULL),
('Папоротник', 'Fern', 0, 34, NULL, NULL),
('Папоротник жареный', 'Fried fern', 0, 80, NULL, NULL),
('Папоротник орляк', 'Bracken fern', 0, 34, NULL, NULL),
('Папоротник соленый', 'Salted fern', 0, 30, NULL, NULL),
('Паприка', 'Paprika', 0, 282, NULL, NULL),
('Паприка копченая', 'Smoked paprika', 0, 282, NULL, NULL),
('Паста болоньезе', 'Pasta bolognese', 0, 140, NULL, NULL),
('Паста из черных бобов', 'Black bean paste', 0, 180, NULL, NULL),
('Паста карбонара', 'Pasta carbonara', 0, 220, NULL, NULL),
('Паста карри вьетнамская', 'Vietnamese curry paste', 0, 120, NULL, NULL),
('Паста томатная', NULL, 0, 91, NULL, NULL),
('Пастернак', 'Parsnip', 0, 75, NULL, NULL),
('Пастила', 'Pastila', 0, 310, NULL, NULL),
('Пастила белёвская', 'Belevskaya pastila', 0, 320, NULL, NULL),
('Патиссон', 'Pattypan squash', 0, 19, NULL, NULL),
('Патока', 'Molasses', 0, 290, NULL, NULL),
('Паштет', 'Pate', 0, 300, NULL, NULL),
('Паштет из печени трески', 'Cod liver pate', 0, 550, NULL, NULL),
('Паштет рыбный', 'Fish pate', 0, 250, NULL, NULL),
('Паэлья', 'Paella', 0, 150, NULL, NULL),
('Пектин', 'Pectin', 0, 325, NULL, NULL),
('Пельмени', 'Pelmeni', 0, 275, NULL, NULL),
('Пельмени жареные', 'Fried pelmeni', 0, 300, NULL, NULL),
('Пельмени китайские', 'Chinese dumplings', 0, 190, NULL, NULL),
('Пельмени отварные', 'Boiled pelmeni', 0, 275, NULL, NULL),
('Пельмени со сметаной', 'Pelmeni with sour cream', 0, 280, NULL, NULL),
('Пепино', 'Pepino melon', 0, 32, NULL, NULL),
('Перец белый молотый', 'Ground white pepper', 0, 296, NULL, NULL),
('Перец болгарский', 'Bell pepper', 0, 27, NULL, NULL),
('Перец душистый', 'Allspice', 0, 263, NULL, NULL),
('Перец кайенский', 'Cayenne pepper', 0, 318, NULL, NULL),
('Перец красный молотый', 'Ground red pepper', 0, 282, NULL, NULL),
('Перец острый', 'Hot pepper', 0, 40, NULL, NULL),
('Перец падрон', 'Padron peppers', 0, 25, NULL, NULL),
('Перец фаршированный', 'Stuffed pepper', 0, 100, NULL, NULL),
('Перец хабанеро', 'Habanero', 0, 40, NULL, NULL),
('Перец халапеньо', 'Jalapeño', 0, 29, NULL, NULL),
('Перец черный горошек', 'Black peppercorns', 0, 251, NULL, NULL),
('Перец черный молотый', 'Ground black pepper', 0, 251, NULL, NULL),
('Перец чили', 'Chili pepper', 0, 40, NULL, NULL),
('Перец шишито', 'Shishito peppers', 0, 25, NULL, NULL),
('Перловка вареная', 'Boiled pearl barley', 0, 109, NULL, NULL),
('Персик', 'Peach', 0, 39, NULL, NULL),
('Персик желтый', 'Yellow peach', 0, 39, NULL, NULL),
('Персики консервированные', 'Canned peaches', 0, 54, NULL, NULL),
('Персики плоские инжирные', 'Flat peaches', 0, 60, NULL, NULL),
('Песто', 'Pesto', 0, 370, NULL, NULL),
('Петрушка', 'Parsley', 0, 47, NULL, NULL),
('Петрушка сушеная', 'Dried parsley', 0, 292, NULL, NULL),
('Печень говяжья', 'Beef liver', 0, 127, NULL, NULL),
('Печень куриная', 'Chicken liver', 0, 136, NULL, NULL),
('Печень трески', 'Cod liver', 0, 613, NULL, NULL),
('Печень трески консервированная', 'Canned cod liver', 0, 613, NULL, NULL),
('Печенье Юбилейное', 'Jubilee cookies', 0, NULL, NULL, 52),
('Печенье овсяное', 'Oatmeal cookies', 0, 437, NULL, NULL),
('Пиво безалкогольное', 'Non-alcoholic beer', 1, 26, 500, NULL),
('Пиво светлое', 'Lager beer', 1, 43, 500, NULL),
('Пиво темное', 'Dark beer', 1, 48, 500, NULL),
('Пина колада', 'Pina colada', 1, 174, 250, NULL),
('Пирожок с капустой', 'Cabbage pie', 0, 220, NULL, NULL),
('Пирожок с мясом', 'Meat pie', 0, 280, NULL, NULL),
('Пирожок с яблоком', 'Apple pie', 0, 240, NULL, NULL),
('Пита', 'Pita', 0, 275, NULL, NULL),
('Питайя желтая', 'Yellow dragon fruit', 0, 60, NULL, NULL),
('Питайя красная', 'Red dragon fruit', 0, 60, NULL, NULL),
('Пицца', 'Pizza', 0, 266, NULL, NULL),
('Пицца Барбекю', 'BBQ pizza', 0, 290, NULL, NULL),
('Пицца Гавайская', 'Hawaiian pizza', 0, 260, NULL, NULL),
('Пицца Диабло', 'Diablo pizza', 0, 290, NULL, NULL),
('Пицца Капричоза', 'Capricciosa pizza', 0, 270, NULL, NULL),
('Пицца Карбонара', 'Carbonara pizza', 0, 300, NULL, NULL),
('Пицца Маргарита', 'Pizza Margherita', 0, 250, NULL, NULL),
('Пицца Маргарита классическая', 'Classic Margherita pizza', 0, 250, NULL, NULL),
('Пицца Мексиканская', 'Mexican pizza', 0, 280, NULL, NULL),
('Пицца Неаполитанская', 'Neapolitan pizza', 0, 255, NULL, NULL),
('Пицца Нью-Йорк', 'New York pizza', 0, 270, NULL, NULL),
('Пицца Пепперони', 'Pepperoni pizza', 0, 280, NULL, NULL),
('Пицца Пепперони классическая', 'Classic pepperoni pizza', 0, 280, NULL, NULL),
('Пицца Римская', 'Roman pizza', 0, 260, NULL, NULL),
('Пицца Сицилийская', 'Sicilian pizza', 0, 270, NULL, NULL),
('Пицца Цезарь', 'Caesar pizza', 0, 270, NULL, NULL),
('Пицца Четыре сезона', 'Four seasons pizza', 0, 270, NULL, NULL),
('Пицца Четыре сыра', 'Four cheese pizza', 0, 300, NULL, NULL),
('Пицца Чикаго', 'Chicago deep-dish pizza', 0, 310, NULL, NULL),
('Пицца без глютена', 'Gluten-free pizza', 0, 240, NULL, NULL),
('Пицца без сыра', 'Cheese-free pizza', 0, 200, NULL, NULL),
('Пицца вегетарианская', 'Vegetarian pizza', 0, 220, NULL, NULL),
('Пицца детская', 'Kids pizza', 0, 260, NULL, NULL),
('Пицца закрытая', 'Closed pizza', 0, 280, NULL, NULL),
('Пицца кальцоне', 'Calzone', 0, 280, NULL, NULL),
('Пицца мясная', 'Meat pizza', 0, 300, NULL, NULL),
('Пицца мясное ассорти', 'Meat assortment pizza', 0, 310, NULL, NULL),
('Пицца на толстом тесте', 'Thick dough pizza', 0, 285, NULL, NULL),
('Пицца на тонком тесте', 'Thin dough pizza', 0, 245, NULL, NULL),
('Пицца острая', 'Spicy pizza', 0, 280, NULL, NULL),
('Пицца половинка', 'Half pizza', 0, 270, NULL, NULL),
('Пицца с ананасом', 'Pineapple pizza', 0, 255, NULL, NULL),
('Пицца с беконом', 'Bacon pizza', 0, 300, NULL, NULL),
('Пицца с ветчиной', 'Ham pizza', 0, 275, NULL, NULL),
('Пицца с ветчиной и ананасом', 'Ham pineapple pizza', 0, 260, NULL, NULL),
('Пицца с ветчиной и грибами', 'Ham mushroom pizza', 0, 270, NULL, NULL),
('Пицца с грибами', 'Mushroom pizza', 0, 250, NULL, NULL),
('Пицца с грушей и горгонзолой', 'Pear gorgonzola pizza', 0, 290, NULL, NULL),
('Пицца с грушей и дорблю', 'Pear blue cheese pizza', 0, 290, NULL, NULL),
('Пицца с дорблю', 'Blue cheese pizza', 0, 300, NULL, NULL),
('Пицца с индейкой', 'Turkey pizza', 0, 255, NULL, NULL),
('Пицца с колбасой', 'Sausage pizza', 0, 285, NULL, NULL),
('Пицца с креветками', 'Shrimp pizza', 0, 245, NULL, NULL),
('Пицца с кукурузой', 'Corn pizza', 0, 250, NULL, NULL),
('Пицца с курицей', 'Chicken pizza', 0, 270, NULL, NULL),
('Пицца с курицей и грибами', 'Chicken mushroom pizza', 0, 265, NULL, NULL),
('Пицца с курицей терияки', 'Teriyaki chicken pizza', 0, 275, NULL, NULL),
('Пицца с лососем', 'Salmon pizza', 0, 255, NULL, NULL),
('Пицца с морепродуктами', 'Seafood pizza', 0, 240, NULL, NULL),
('Пицца с моцареллой', 'Mozzarella pizza', 0, 260, NULL, NULL),
('Пицца с нутеллой', 'Nutella pizza', 0, 350, NULL, NULL),
('Пицца с овощами', 'Vegetable pizza', 0, 220, NULL, NULL),
('Пицца с охотничьими колбасками', 'Hunter sausage pizza', 0, 295, NULL, NULL),
('Пицца с пармезаном', 'Parmesan pizza', 0, 280, NULL, NULL),
('Пицца с перцем халапеньо', 'Jalapeño pizza', 0, 275, NULL, NULL),
('Пицца с прошутто', 'Prosciutto pizza', 0, 280, NULL, NULL),
('Пицца с рукколой', 'Arugula pizza', 0, 240, NULL, NULL),
('Пицца с рукколой и пармезаном', 'Arugula parmesan pizza', 0, 255, NULL, NULL),
('Пицца с салями', 'Salami pizza', 0, 290, NULL, NULL),
('Пицца с сыром фета', 'Feta pizza', 0, 270, NULL, NULL),
('Пицца с томатами и моцареллой', 'Tomato mozzarella pizza', 0, 250, NULL, NULL),
('Пицца с тунцом', 'Tuna pizza', 0, 250, NULL, NULL),
('Пицца с чоризо', 'Chorizo pizza', 0, 295, NULL, NULL),
('Пицца с яблоками', 'Apple pizza', 0, 280, NULL, NULL),
('Пицца сладкая', 'Sweet pizza', 0, 300, NULL, NULL),
('Пицца толстая', 'Thick crust pizza', 0, 280, NULL, NULL),
('Пицца тонкая', 'Thin crust pizza', 0, 250, NULL, NULL),
('Пищевой краситель', 'Food coloring', 0, 0, NULL, NULL),
('Плантайн', 'Plantain', 0, 122, NULL, NULL),
('Плов', 'Pilaf', 0, 150, NULL, NULL),
('Плотва', 'Roach', 0, 88, NULL, NULL),
('Помело', 'Pomelo', 0, 38, NULL, NULL),
('Помело красное', 'Red pomelo', 0, 38, NULL, NULL),
('Помидор бычье сердце', 'Beefsteak tomato', 0, 18, NULL, NULL),
('Помидор желтый', 'Yellow tomato', 0, 18, NULL, NULL),
('Помидор розовый', 'Pink tomato', 0, 18, NULL, NULL),
('Помидоры', 'Tomatoes', 0, 20, NULL, NULL),
('Помидоры черри', 'Cherry tomatoes', 0, 18, NULL, NULL),
('Пончик', 'Donut', 0, 421, NULL, NULL),
('Попкорн', 'Popcorn', 0, 375, NULL, NULL),
('Попкорн сладкий', 'Sweet popcorn', 0, 420, NULL, NULL),
('Портвейн', 'Port wine', 1, 157, 50, NULL),
('Приправа', 'Seasoning', 0, 200, NULL, NULL),
('Приправа для курицы', 'Chicken seasoning', 0, 250, NULL, NULL),
('Приправа для мяса', 'Meat seasoning', 0, 250, NULL, NULL),
('Приправа для плова', 'Pilaf seasoning', 0, 250, NULL, NULL),
('Приправа для рыбы', 'Fish seasoning', 0, 250, NULL, NULL),
('Прованские травы', 'Herbes de Provence', 0, 250, NULL, NULL),
('Просекко', 'Prosecco', 1, 70, 150, NULL),
('Простокваша', 'Prostokvasha', 1, 58, NULL, NULL),
('Протеиновый батончик', 'Protein bar', 0, 360, NULL, NULL),
('Протеиновый коктейль', 'Protein shake', 1, 80, 300, NULL),
('Профитроли', 'Profiteroles', 0, 340, NULL, NULL),
('Пряник', 'Gingerbread', 0, 350, NULL, NULL),
('Пряники тульские', 'Tula gingerbread', 0, 360, NULL, NULL),
('Псиллиум', NULL, 0, 42, 10, NULL),
('Пшенная каша', 'Millet porridge', 0, 90, NULL, NULL),
('Рагу мясное', 'Meat stew', 0, 130, NULL, NULL),
('Радиччо', 'Radicchio', 0, 23, NULL, NULL),
('Разрыхлитель', 'Baking powder', 0, 53, NULL, NULL),
('Разрыхлитель для выпечки', 'Baking powder for baking', 0, 53, NULL, NULL),
('Разрыхлитель для теста', 'Baking powder', 0, 53, NULL, NULL),
('Разрыхлитель пекарский', 'Baker''s baking powder', 0, 53, NULL, NULL),
('Разрыхлитель теста', 'Baking powder', 0, 53, NULL, NULL),
('Разрыхлитель теста Dr. Oetker', 'Dr. Oetker baking powder', 0, 53, NULL, NULL),
('Разрыхлитель теста безфосфатный', 'Phosphate-free baking powder', 0, 53, NULL, NULL),
('Разрыхлитель теста с ванилином', 'Baking powder with vanillin', 0, 80, NULL, NULL),
('Рамбутан', 'Rambutan', 0, 82, NULL, NULL),
('Рамен', 'Ramen', 0, 100, NULL, NULL),
('Рассольник', 'Rassolnik', 0, 50, NULL, NULL),
('Рассольник ленинградский', 'Leningrad rassolnik', 0, 55, NULL, NULL),
('Растительное масло', 'Vegetable oil', 0, 899, NULL, NULL),
('Рататуй', 'Ratatouille', 0, 50, NULL, NULL),
('Раф кофе', 'Raf coffee', 1, 90, 250, NULL),
('Ребрышки в кисло-сладком соусе', 'Sweet and sour ribs', 0, 260, NULL, NULL),
('Редис', NULL, 0, 16, NULL, NULL),
('Редис розовый', 'Pink radish', 0, 16, NULL, NULL),
('Редька белая', 'White radish', 0, 21, NULL, NULL),
('Редька зеленая', 'Green radish', 0, 32, NULL, NULL),
('Редька черная', 'Black radish', 0, 35, NULL, NULL),
('Репа', 'Turnip', 0, 28, NULL, NULL),
('Ризотто', 'Risotto', 0, 140, NULL, NULL),
('Рис бурый вареный', 'Boiled brown rice', 0, 110, NULL, NULL),
('Рис вареный', 'Boiled rice', 0, 116, NULL, NULL),
('Рис вьетнамский на пару', 'Vietnamese steamed rice', 0, 130, NULL, NULL),
('Рис жареный', 'Fried rice', 0, 160, NULL, NULL),
('Рис жареный с креветками', 'Shrimp fried rice', 0, 155, NULL, NULL),
('Рис жареный с курицей', 'Chicken fried rice', 0, 165, NULL, NULL),
('Рис жареный с яйцом', 'Egg fried rice', 0, 160, NULL, NULL),
('Рис жареный янчжоу', 'Yangzhou fried rice', 0, 170, NULL, NULL),
('Рис жасмин', 'Jasmine rice', 0, 130, NULL, NULL),
('Рис клейкий', 'Sticky rice', 0, 150, NULL, NULL),
('Рис клейкий с манго', 'Mango sticky rice', 0, 200, NULL, NULL),
('Рис на пару', 'Steamed rice', 0, 130, NULL, NULL),
('Рис сухой', 'Dry rice', 0, 344, NULL, NULL),
('Розмарин', 'Rosemary', 0, 131, NULL, NULL),
('Розмарин сушеный', 'Dried rosemary', 0, 331, NULL, NULL),
('Ролл Аляска', 'Alaska roll', 0, 170, NULL, NULL),
('Ролл Бонито', 'Bonito roll', 0, 165, NULL, NULL),
('Ролл Дракон', 'Dragon roll', 0, 190, NULL, NULL),
('Ролл Калифорния', 'California roll', 0, 155, NULL, NULL),
('Ролл Калифорния с крабом', 'California roll with crab', 0, 155, NULL, NULL),
('Ролл Калифорния с креветкой', 'California roll with shrimp', 0, 150, NULL, NULL),
('Ролл Канада', 'Canada roll', 0, 200, NULL, NULL),
('Ролл Каппа маки', 'Kappa maki', 0, 115, NULL, NULL),
('Ролл Маки', 'Maki roll', 0, 145, NULL, NULL),
('Ролл Радуга', 'Rainbow roll', 0, 175, NULL, NULL),
('Ролл Сяке маки', 'Sake maki', 0, 155, NULL, NULL),
('Ролл Текка маки', 'Tekka maki', 0, 145, NULL, NULL),
('Ролл Унаги маки', 'Unagi maki', 0, 185, NULL, NULL),
('Ролл Урамаки', 'Uramaki', 0, 165, NULL, NULL),
('Ролл Филадельфия', 'Philadelphia roll', 0, 180, NULL, NULL),
('Ролл Филадельфия классический', 'Classic Philadelphia roll', 0, 180, NULL, NULL),
('Ролл Филадельфия с авокадо', 'Philadelphia roll with avocado', 0, 185, NULL, NULL),
('Ролл Филадельфия с огурцом', 'Philadelphia roll with cucumber', 0, 170, NULL, NULL),
('Ролл Футомаки', 'Futomaki', 0, 160, NULL, NULL),
('Ролл Хосомаки', 'Hosomaki', 0, 140, NULL, NULL),
('Ролл Цезарь', 'Caesar roll', 0, 180, NULL, NULL),
('Ролл в икре', 'Roe-wrapped roll', 0, 175, NULL, NULL),
('Ролл в кунжуте', 'Sesame roll', 0, 170, NULL, NULL),
('Ролл в стружке тунца', 'Bonito flake roll', 0, 165, NULL, NULL),
('Ролл в темпуре', 'Tempura-wrapped roll', 0, 230, NULL, NULL),
('Ролл вегетарианский', 'Vegetarian roll', 0, 130, NULL, NULL),
('Ролл горячий', 'Hot roll', 0, 220, NULL, NULL),
('Ролл жареный', 'Fried roll', 0, 230, NULL, NULL),
('Ролл запеченный', 'Baked roll', 0, 190, NULL, NULL),
('Ролл запеченный с гребешком', 'Baked scallop roll', 0, 185, NULL, NULL),
('Ролл запеченный с креветкой', 'Baked shrimp roll', 0, 185, NULL, NULL),
('Ролл запеченный с лососем', 'Baked salmon roll', 0, 200, NULL, NULL),
('Ролл запеченный с мидиями', 'Baked mussel roll', 0, 180, NULL, NULL),
('Ролл запеченный с угрем', 'Baked eel roll', 0, 210, NULL, NULL),
('Ролл зеленый дракон', 'Green dragon roll', 0, 185, NULL, NULL),
('Ролл красный дракон', 'Red dragon roll', 0, 190, NULL, NULL),
('Ролл овощной', 'Vegetable roll', 0, 130, NULL, NULL),
('Ролл острый', 'Spicy roll', 0, 175, NULL, NULL),
('Ролл острый с креветкой', 'Spicy shrimp roll', 0, 165, NULL, NULL),
('Ролл острый с лососем', 'Spicy salmon roll', 0, 180, NULL, NULL),
('Ролл острый с тунцом', 'Spicy tuna roll', 0, 170, NULL, NULL),
('Ролл с авокадо', 'Avocado roll', 0, 145, NULL, NULL),
('Ролл с беконом', 'Bacon roll', 0, 200, NULL, NULL),
('Ролл с икрой', 'Roe roll', 0, 170, NULL, NULL),
('Ролл с крабом', 'Crab roll', 0, 155, NULL, NULL),
('Ролл с крабом и авокадо', 'Crab avocado roll', 0, 155, NULL, NULL),
('Ролл с креветкой', 'Shrimp roll', 0, 150, NULL, NULL),
('Ролл с креветкой и авокадо', 'Shrimp avocado roll', 0, 155, NULL, NULL),
('Ролл с креветкой и сыром', 'Shrimp cheese roll', 0, 175, NULL, NULL),
('Ролл с курицей', 'Chicken roll', 0, 170, NULL, NULL),
('Ролл с курицей терияки', 'Teriyaki chicken roll', 0, 175, NULL, NULL),
('Ролл с лососем', 'Salmon roll', 0, 170, NULL, NULL),
('Ролл с лососем и авокадо', 'Salmon avocado roll', 0, 175, NULL, NULL),
('Ролл с лососем и огурцом', 'Salmon cucumber roll', 0, 160, NULL, NULL),
('Ролл с лососем и сыром', 'Salmon cheese roll', 0, 185, NULL, NULL),
('Ролл с масаго', 'Masago roll', 0, 160, NULL, NULL),
('Ролл с огурцом', 'Cucumber roll', 0, 120, NULL, NULL),
('Ролл с сыром', 'Cheese roll', 0, 180, NULL, NULL),
('Ролл с творожным сыром', 'Cream cheese curd roll', 0, 185, NULL, NULL),
('Ролл с тобико', 'Tobiko roll', 0, 165, NULL, NULL),
('Ролл с тунцом', 'Tuna roll', 0, 160, NULL, NULL),
('Ролл с тунцом и авокадо', 'Tuna avocado roll', 0, 165, NULL, NULL),
('Ролл с угрем', 'Eel roll', 0, 200, NULL, NULL),
('Ролл с угрем в соусе унаги', 'Unagi sauce eel roll', 0, 210, NULL, NULL),
('Ролл с угрем и авокадо', 'Eel avocado roll', 0, 195, NULL, NULL),
('Ролл с угрем и сыром', 'Eel cheese roll', 0, 210, NULL, NULL),
('Ролл с чукой', 'Chuka roll', 0, 140, NULL, NULL),
('Ролл сет', 'Roll set', 0, 170, NULL, NULL),
('Ролл сет Филадельфия', 'Philadelphia roll set', 0, 180, NULL, NULL),
('Ролл сет большой', 'Large roll set', 0, 175, NULL, NULL),
('Ролл сет горячий', 'Hot roll set', 0, 210, NULL, NULL),
('Ролл сет запеченный', 'Baked roll set', 0, 195, NULL, NULL),
('Ролл со сливочным сыром', 'Cream cheese roll', 0, 185, NULL, NULL),
('Ролл темпура', 'Tempura roll', 0, 220, NULL, NULL),
('Ролл темпура с креветкой', 'Shrimp tempura roll', 0, 230, NULL, NULL),
('Ролл темпура с лососем', 'Salmon tempura roll', 0, 235, NULL, NULL),
('Ролл черный дракон', 'Black dragon roll', 0, 195, NULL, NULL),
('Роллы', 'Sushi rolls', 0, 160, NULL, NULL),
('Роллы жареные вьетнамские', 'Vietnamese fried rolls', 0, 240, NULL, NULL),
('Роллы с креветками вьетнамские', 'Vietnamese shrimp rolls', 0, 95, NULL, NULL),
('Роллы с курицей вьетнамские', 'Vietnamese chicken rolls', 0, 100, NULL, NULL),
('Ром', 'Rum', 1, 231, 50, NULL),
('Романо капуста', 'Romaine hearts', 0, 17, NULL, NULL),
('Ростки люцерны', 'Alfalfa sprouts', 0, 23, NULL, NULL),
('Ростки маша', 'Mung bean sprouts', 0, 30, NULL, NULL),
('Ростки сои', 'Soybean sprouts', 0, 30, NULL, NULL),
('Руккола', 'Arugula', 0, 25, NULL, NULL),
('Рыба в кисло-сладком соусе', 'Sweet and sour fish', 0, 180, NULL, NULL),
('Рыба в масле', 'Fish in oil', 0, 250, NULL, NULL),
('Рыба в томате', 'Fish in tomato sauce', 0, 120, NULL, NULL),
('Рыба вареная', 'Boiled fish', 0, 90, NULL, NULL),
('Рыба вяленая', 'Cured dried fish', 0, 220, NULL, NULL),
('Рыба горячего копчения', 'Hot-smoked fish', 0, 180, NULL, NULL),
('Рыба жареная', 'Fried fish', 0, 190, NULL, NULL),
('Рыба запеченная', 'Baked fish', 0, 120, NULL, NULL),
('Рыба на гриле', 'Grilled fish', 0, 140, NULL, NULL),
('Рыба на пару', 'Steamed fish', 0, 100, NULL, NULL),
('Рыба слабосоленая', 'Lightly salted fish', 0, 140, NULL, NULL),
('Рыба соленая', 'Salted fish', 0, 150, NULL, NULL),
('Рыба холодного копчения', 'Cold-smoked fish', 0, 160, NULL, NULL),
('Рыбные котлеты', 'Fish cutlets', 0, 160, NULL, NULL),
('Рыбные палочки', 'Fish sticks', 0, 200, NULL, NULL),
('Рыбные тефтели', 'Fish meatballs', 0, 140, NULL, NULL),
('Рыбный суп', 'Fish soup', 0, 40, NULL, NULL),
('Рябина', 'Rowan', 0, 50, NULL, NULL),
('Рябина черноплодная', 'Aronia', 0, 55, NULL, NULL),
('Ряженка 2,5%', 'Ryazhenka 2.5%', 1, 54, NULL, NULL),
('Ряженка 4%', 'Ryazhenka 4%', 1, 67, NULL, NULL),
('Сазан', 'Common carp', 0, 121, NULL, NULL),
('Сайра', 'Saury', 0, 205, NULL, NULL),
('Сайра в масле', 'Saury in oil', 0, 280, NULL, NULL),
('Сайра копченая', 'Smoked saury', 0, 220, NULL, NULL),
('Саке', 'Sake', 1, 134, 100, NULL),
('Салак', 'Salak', 0, 82, NULL, NULL),
('Салат Вальдорф', 'Waldorf salad', 0, 150, NULL, NULL),
('Салат Весенний', 'Spring salad', 0, 50, NULL, NULL),
('Салат Винегрет', 'Vinaigrette salad', 0, 130, NULL, NULL),
('Салат Гнездо глухаря', 'Grouse nest salad', 0, 200, NULL, NULL),
('Салат Греческий с фетой', 'Greek salad with feta', 0, 130, NULL, NULL),
('Салат Грибная поляна', 'Mushroom meadow salad', 0, 190, NULL, NULL),
('Салат Дамский каприз', 'Ladies'' whim salad', 0, 180, NULL, NULL),
('Салат Ежик', 'Hedgehog salad', 0, 180, NULL, NULL),
('Салат Капрезе', 'Caprese salad', 0, 150, NULL, NULL),
('Салат Кобб', 'Cobb salad', 0, 170, NULL, NULL),
('Салат Крабовый', 'Crab salad', 0, 180, NULL, NULL),
('Салат Крабовый с кукурузой', 'Crab salad with corn', 0, 175, NULL, NULL),
('Салат Лаб', 'Larb salad', 0, 120, NULL, NULL),
('Салат Летний', 'Summer salad', 0, 45, NULL, NULL),
('Салат Мимоза', 'Mimosa salad', 0, 200, NULL, NULL),
('Салат Мимоза с сайрой', 'Mimosa salad with saury', 0, 210, NULL, NULL),
('Салат Мужской каприз', 'Men''s whim salad', 0, 200, NULL, NULL),
('Салат Невеста', 'Nevesta salad', 0, 190, NULL, NULL),
('Салат Нисуаз', 'Nicoise salad', 0, 140, NULL, NULL),
('Салат Обжорка', 'Obzhorka salad', 0, 210, NULL, NULL),
('Салат Оливье', 'Olivier salad', 0, 160, NULL, NULL),
('Салат Оливье классический', 'Classic Olivier salad', 0, 160, NULL, NULL),
('Салат Осенний', 'Autumn salad', 0, 80, NULL, NULL),
('Салат Подсолнух', 'Sunflower salad', 0, 220, NULL, NULL),
('Салат Радуга', 'Rainbow salad', 0, 100, NULL, NULL),
('Салат Селедка под шубой', 'Herring under a fur coat salad', 0, 193, NULL, NULL),
('Салат Сом там', 'Som tam', 0, 55, NULL, NULL),
('Салат Столичный', 'Capital salad', 0, 217, NULL, NULL),
('Салат Столичный классический', 'Classic Capital salad', 0, 217, NULL, NULL),
('Салат Тайский с говядиной', 'Thai beef salad', 0, 130, NULL, NULL),
('Салат Тайский с креветками', 'Thai shrimp salad', 0, 110, NULL, NULL),
('Салат Теплый с говядиной', 'Warm beef salad', 0, 160, NULL, NULL),
('Салат Теплый с курицей', 'Warm chicken salad', 0, 150, NULL, NULL),
('Салат Теплый с морепродуктами', 'Warm seafood salad', 0, 140, NULL, NULL),
('Салат Цезарь', 'Caesar salad', 0, 190, NULL, NULL),
('Салат Цезарь с креветками', 'Caesar salad with shrimp', 0, 160, NULL, NULL),
('Салат Цезарь с курицей', 'Caesar salad with chicken', 0, 180, NULL, NULL),
('Салат Шапка Мономаха', 'Monomakh''s Cap salad', 0, 230, NULL, NULL),
('Салат Шопский', 'Shopska salad', 0, 80, NULL, NULL),
('Салат Ям вон сен', 'Yam woon sen', 0, 100, NULL, NULL),
('Салат айсберг', 'Iceberg lettuce', 0, 14, NULL, NULL),
('Салат айсберг с соусом', 'Iceberg salad with dressing', 0, 80, NULL, NULL),
('Салат боул', 'Salad bowl', 0, 120, NULL, NULL),
('Салат боул с креветками', 'Shrimp salad bowl', 0, 120, NULL, NULL),
('Салат боул с курицей', 'Chicken salad bowl', 0, 140, NULL, NULL),
('Салат вьетнамский гой', 'Vietnamese goi salad', 0, 80, NULL, NULL),
('Салат грибной', 'Mushroom salad', 0, 100, NULL, NULL),
('Салат дайкон', 'Daikon salad', 0, 35, NULL, NULL),
('Салат зеленый', 'Green salad', 0, 25, NULL, NULL),
('Салат из авокадо', 'Avocado salad', 0, 140, NULL, NULL),
('Салат из баклажанов', 'Eggplant salad', 0, 90, NULL, NULL),
('Салат из белокочанной капусты', 'White cabbage salad', 0, 40, NULL, NULL),
('Салат из болгарского перца', 'Bell pepper salad', 0, 50, NULL, NULL),
('Салат из водорослей', 'Seaweed salad', 0, 50, NULL, NULL),
('Салат из зеленой папайи', 'Green papaya salad', 0, 55, NULL, NULL),
('Салат из кабачков', 'Zucchini salad', 0, 60, NULL, NULL),
('Салат из кальмаров', 'Squid salad', 0, 100, NULL, NULL),
('Салат из капусты свежей', 'Fresh cabbage salad', 0, 40, NULL, NULL),
('Салат из краснокочанной капусты', 'Red cabbage salad', 0, 45, NULL, NULL),
('Салат из креветок', 'Shrimp salad', 0, 100, NULL, NULL),
('Салат из мидий', 'Mussel salad', 0, 90, NULL, NULL),
('Салат из морской капусты', 'Seaweed salad', 0, 50, NULL, NULL),
('Салат из огурцов и помидоров', 'Cucumber tomato salad', 0, 35, NULL, NULL),
('Салат из папоротника', 'Fern salad', 0, 70, NULL, NULL),
('Салат из пекинской капусты', 'Napa cabbage salad', 0, 35, NULL, NULL),
('Салат из редиса', 'Radish salad', 0, 40, NULL, NULL),
('Салат из редьки', 'Daikon radish salad', 0, 35, NULL, NULL),
('Салат из ростков маша', 'Mung bean sprout salad', 0, 40, NULL, NULL),
('Салат из ростков сои', 'Soybean sprout salad', 0, 45, NULL, NULL),
('Салат из свежих овощей', 'Fresh vegetable salad', 0, 40, NULL, NULL),
('Салат из свежих овощей с зеленью', 'Fresh vegetables with herbs salad', 0, 40, NULL, NULL),
('Салат из свеклы', 'Beetroot salad', 0, 70, NULL, NULL),
('Салат из свеклы с чесноком', 'Beetroot salad with garlic', 0, 90, NULL, NULL),
('Салат из яблок и моркови', 'Apple carrot salad', 0, 60, NULL, NULL),
('Салат капуста с морковью', 'Cabbage carrot salad', 0, 50, NULL, NULL),
('Салат картофельный', 'Potato salad', 0, 140, NULL, NULL),
('Салат картофельный немецкий', 'German potato salad', 0, 130, NULL, NULL),
('Салат кимчи', 'Kimchi salad', 0, 20, NULL, NULL),
('Салат китайский овощной', 'Chinese vegetable salad', 0, 60, NULL, NULL),
('Салат китайский с лапшой', 'Chinese noodle salad', 0, 140, NULL, NULL),
('Салат коул слоу классический', 'Classic coleslaw', 0, 120, NULL, NULL),
('Салат латук', 'Lettuce', 0, 15, NULL, NULL),
('Салат лечо-салат', 'Lecho-style salad', 0, 70, NULL, NULL),
('Салат микс листьев', 'Mixed leaf salad', 0, 30, NULL, NULL),
('Салат морковь по-корейски', 'Korean carrot salad', 0, 110, NULL, NULL),
('Салат овощной с майонезом', 'Vegetable salad with mayonnaise', 0, 120, NULL, NULL),
('Салат овощной с маслом', 'Vegetable salad with oil', 0, 55, NULL, NULL),
('Салат овощной со сметаной', 'Vegetable salad with sour cream', 0, 70, NULL, NULL),
('Салат паста', 'Pasta salad', 0, 160, NULL, NULL),
('Салат поке', 'Poke salad', 0, 130, NULL, NULL),
('Салат поке с лососем', 'Salmon poke', 0, 150, NULL, NULL),
('Салат поке с тунцом', 'Tuna poke', 0, 140, NULL, NULL),
('Салат романо', 'Romaine lettuce', 0, 17, NULL, NULL),
('Салат с авокадо и креветками', 'Avocado shrimp salad', 0, 130, NULL, NULL),
('Салат с адыгейским сыром', 'Adyghe cheese salad', 0, 130, NULL, NULL),
('Салат с апельсином и рукколой', 'Orange arugula salad', 0, 70, NULL, NULL),
('Салат с брынзой', 'Bryndza salad', 0, 130, NULL, NULL),
('Салат с булгуром', 'Bulgur salad', 0, 110, NULL, NULL),
('Салат с ветчиной и сыром', 'Ham and cheese salad', 0, 180, NULL, NULL),
('Салат с говядиной', 'Beef salad', 0, 150, NULL, NULL),
('Салат с гранатом', 'Pomegranate salad', 0, 80, NULL, NULL),
('Салат с грецкими орехами', 'Walnut salad', 0, 160, NULL, NULL),
('Салат с грибами маринованными', 'Pickled mushroom salad', 0, 90, NULL, NULL),
('Салат с икрой', 'Caviar salad', 0, 180, NULL, NULL),
('Салат с кедровыми орехами', 'Pine nut salad', 0, 170, NULL, NULL),
('Салат с киноа', 'Quinoa salad', 0, 120, NULL, NULL),
('Салат с киноа и курицей', 'Quinoa chicken salad', 0, 140, NULL, NULL),
('Салат с киноа и овощами', 'Quinoa vegetable salad', 0, 115, NULL, NULL),
('Салат с крабовыми палочками', 'Imitation crab salad', 0, 170, NULL, NULL),
('Салат с красной икрой', 'Red caviar salad', 0, 160, NULL, NULL),
('Салат с креветками', 'Shrimp salad', 0, 100, NULL, NULL),
('Салат с кунжутом', 'Sesame salad', 0, 120, NULL, NULL),
('Салат с курагой и курицей', 'Dried apricot chicken salad', 0, 150, NULL, NULL),
('Салат с курицей и ананасом', 'Chicken pineapple salad', 0, 140, NULL, NULL),
('Салат с курицей и грибами', 'Chicken mushroom salad', 0, 150, NULL, NULL),
('Салат с курицей и овощами', 'Chicken vegetable salad', 0, 120, NULL, NULL),
('Салат с курицей и сыром', 'Chicken cheese salad', 0, 160, NULL, NULL),
('Салат с лососем', 'Salmon salad', 0, 150, NULL, NULL),
('Салат с моцареллой', 'Mozzarella salad', 0, 140, NULL, NULL),
('Салат с нутом', 'Chickpea salad', 0, 120, NULL, NULL),
('Салат с печенью', 'Liver salad', 0, 140, NULL, NULL),
('Салат с печенью трески', 'Cod liver salad', 0, 250, NULL, NULL),
('Салат с рукколой и пармезаном', 'Arugula parmesan salad', 0, 120, NULL, NULL),
('Салат с рукколой и томатами', 'Arugula tomato salad', 0, 70, NULL, NULL),
('Салат с семечками', 'Sunflower seed salad', 0, 130, NULL, NULL),
('Салат с сердцем', 'Heart salad', 0, 130, NULL, NULL),
('Салат с сулугуни', 'Suluguni salad', 0, 140, NULL, NULL),
('Салат с творогом', 'Cottage cheese salad', 0, 100, NULL, NULL),
('Салат с тофу', 'Tofu salad', 0, 90, NULL, NULL),
('Салат с тунцом', 'Tuna salad', 0, 120, NULL, NULL),
('Салат с тунцом и яйцом', 'Tuna egg salad', 0, 130, NULL, NULL),
('Салат с фасолью', 'Bean salad', 0, 110, NULL, NULL),
('Салат с фетой и оливками', 'Feta olive salad', 0, 135, NULL, NULL),
('Салат с черносливом', 'Prune salad', 0, 140, NULL, NULL),
('Салат с чечевицей', 'Lentil salad', 0, 110, NULL, NULL),
('Салат с шампиньонами', 'Champignon salad', 0, 100, NULL, NULL),
('Салат с языком', 'Tongue salad', 0, 160, NULL, NULL),
('Салат с яйцом и зеленым луком', 'Egg green onion salad', 0, 120, NULL, NULL),
('Салат табуле', 'Tabbouleh', 0, 85, NULL, NULL),
('Салат фатуш', 'Fattoush', 0, 90, NULL, NULL),
('Салат фруктовый', 'Fruit salad', 0, 50, NULL, NULL),
('Салат чука', 'Chuka salad', 0, 70, NULL, NULL),
('Салат яичный', 'Egg salad', 0, 180, NULL, NULL),
('Сало', 'Pork fat salo', 0, 797, NULL, NULL),
('Сало копченое', 'Smoked salo', 0, 750, NULL, NULL),
('Сало соленое', 'Salted salo', 0, 800, NULL, NULL),
('Сальса', 'Salsa', 0, 36, NULL, NULL),
('Самбука', 'Sambuca', 1, 240, 40, NULL),
('Самогон', 'Moonshine', 1, 235, 50, NULL),
('Самса', 'Samsa', 0, 290, NULL, NULL),
('Саподилла', 'Sapodilla', 0, 83, NULL, NULL),
('Сардельки', 'Sardelki', 0, 280, NULL, NULL),
('Сардины', 'Sardines', 0, 208, NULL, NULL),
('Сардины в масле', 'Sardines in oil', 0, 250, NULL, NULL),
('Сардины в томате', 'Sardines in tomato', 0, 160, NULL, NULL),
('Сахар', 'Sugar', 0, 387, NULL, NULL),
('Сахар ванильный', 'Vanilla sugar', 0, 395, NULL, NULL),
('Сахар коричневый', 'Brown sugar', 0, 380, NULL, NULL),
('Сахар тростниковый', 'Cane sugar', 0, 398, NULL, NULL),
('Сахарная пудра', 'Powdered sugar', 0, 374, NULL, NULL),
('Сашими', 'Sashimi', 0, 120, NULL, NULL),
('Сашими ассорти', 'Sashimi assortment', 0, 135, NULL, NULL),
('Сашими из лосося', 'Salmon sashimi', 0, 140, NULL, NULL),
('Сашими из тунца', 'Tuna sashimi', 0, 130, NULL, NULL),
('Сашими из угря', 'Eel sashimi', 0, 180, NULL, NULL),
('Сванская соль', 'Svanetian salt', 0, 50, NULL, NULL),
('Свекла', 'Beetroot', 0, 43, NULL, NULL),
('Свекла вареная', 'Boiled beetroot', 0, 49, NULL, NULL),
('Свинина', 'Pork', 0, 242, NULL, NULL),
('Свинина в кисло-сладком соусе', 'Sweet and sour pork', 0, 220, NULL, NULL),
('Свинина дважды приготовленная', 'Twice-cooked pork', 0, 260, NULL, NULL),
('Свинина на гриле вьетнамская', 'Vietnamese grilled pork', 0, 220, NULL, NULL),
('Свинина ча сиу', 'Char siu pork', 0, 250, NULL, NULL),
('Свити', 'Oroblanco', 0, 38, NULL, NULL),
('Сгущенка', 'Condensed milk', 0, 330, NULL, NULL),
('Сгущенка вареная', 'Boiled condensed milk', 0, 320, NULL, NULL),
('Сгущенное молоко вареное', 'Boiled condensed milk', 0, 320, NULL, NULL),
('Севрюга', 'Sevruga', 0, 160, NULL, NULL),
('Сейтан', 'Seitan', 0, 120, NULL, NULL),
('Селедка под шубой', 'Herring under a fur coat', 0, 193, NULL, NULL),
('Сельдерей', 'Celery', 0, 16, NULL, NULL),
('Сельдь', 'Herring', 0, 161, NULL, NULL),
('Сельдь в вине', 'Herring in wine', 0, 160, NULL, NULL),
('Сельдь в масле', 'Herring in oil', 0, 270, NULL, NULL),
('Сельдь горячего копчения', 'Hot-smoked herring', 0, 210, NULL, NULL),
('Сельдь жирная', 'Fatty herring', 0, 217, NULL, NULL),
('Сельдь иваси', 'Iwashi herring', 0, 172, NULL, NULL),
('Сельдь иваси слабосоленая', 'Lightly salted iwashi', 0, 180, NULL, NULL),
('Сельдь копченая', 'Smoked herring', 0, 200, NULL, NULL),
('Сельдь маринованная', 'Pickled herring', 0, 150, NULL, NULL),
('Сельдь под шубой классическая', 'Classic herring under fur coat', 0, 193, NULL, NULL),
('Сельдь слабосоленая', 'Lightly salted herring', 0, 170, NULL, NULL),
('Сельдь соленая', 'Salted herring', 0, 217, NULL, NULL),
('Сельдь филе', 'Herring fillet', 0, 161, NULL, NULL),
('Сельдь холодного копчения', 'Cold-smoked herring', 0, 190, NULL, NULL),
('Семена горчицы', 'Mustard seeds', 0, 508, NULL, NULL),
('Семена кунжута белые', 'White sesame seeds', 0, 565, NULL, NULL),
('Семена кунжута черные', 'Black sesame seeds', 0, 565, NULL, NULL),
('Семена льна', 'Flax seeds', 0, 534, NULL, NULL),
('Семена подсолнечника очищенные', 'Shelled sunflower seeds', 0, 578, NULL, NULL),
('Семена тмина', 'Caraway seeds', 0, 333, NULL, NULL),
('Семена чиа', 'Chia seeds', 0, 486, NULL, NULL),
('Семечки подсолнечника', 'Sunflower seeds', 0, 601, NULL, NULL),
('Семечки тыквенные', 'Pumpkin seeds', 0, 559, NULL, NULL),
('Сердце куриное', 'Chicken heart', 0, 159, NULL, NULL),
('Сибас', 'Seabass', 0, 97, NULL, NULL),
('Сибас запеченный', 'Baked seabass', 0, 110, NULL, NULL),
('Сибас на гриле', 'Grilled seabass', 0, 120, NULL, NULL),
('Сидр', 'Cider', 1, 48, 250, NULL),
('Сироп агавы', 'Agave syrup', 0, 310, NULL, NULL),
('Сироп кленовый', 'Maple syrup', 0, 260, NULL, NULL),
('Скорцонера', 'Black salsify', 0, 82, NULL, NULL),
('Скрэмбл', 'Scrambled eggs', 0, 160, NULL, NULL),
('Скумбрия', 'Mackerel', 0, 191, NULL, NULL),
('Скумбрия в масле', 'Mackerel in oil', 0, 278, NULL, NULL),
('Скумбрия горячего копчения', 'Hot-smoked mackerel', 0, 230, NULL, NULL),
('Скумбрия жареная', 'Fried mackerel', 0, 240, NULL, NULL),
('Скумбрия запеченная', 'Baked mackerel', 0, 210, NULL, NULL),
('Скумбрия копченая', 'Smoked mackerel', 0, 220, NULL, NULL),
('Скумбрия слабосоленая', 'Lightly salted mackerel', 0, 200, NULL, NULL),
('Скумбрия соленая', 'Salted mackerel', 0, 210, NULL, NULL),
('Скумбрия холодного копчения', 'Cold-smoked mackerel', 0, 210, NULL, NULL),
('Слабосоленый лосось', 'Lightly salted salmon', 0, 202, NULL, NULL),
('Слива', 'Plum', 0, 46, NULL, NULL),
('Слива венгерка', 'Hungarian plum', 0, 46, NULL, NULL),
('Сливки 10%', 'Cream 10%', 1, 119, NULL, NULL),
('Сливки 20%', 'Cream 20%', 1, 205, NULL, NULL),
('Сливки 33%', 'Cream 33%', 1, 322, NULL, NULL),
('Смесь овощная замороженная', 'Frozen vegetable mix', 0, 40, NULL, NULL),
('Смесь перцев', 'Pepper mix', 0, 255, NULL, NULL),
('Сметана 10%', 'Sour cream 10%', 0, 115, NULL, NULL),
('Сметана 15%', 'Sour cream 15%', 0, 158, NULL, NULL),
('Сметана 20%', 'Sour cream 20%', 0, 206, NULL, NULL),
('Сметана 25%', 'Sour cream 25%', 0, 248, NULL, NULL),
('Сметана 30%', 'Sour cream 30%', 0, 294, NULL, NULL),
('Смородина белая', 'White currant', 0, 42, NULL, NULL),
('Смузи', 'Smoothie', 1, 60, 250, NULL),
('Смузи из авокадо вьетнамский', 'Vietnamese avocado smoothie', 1, 100, 300, NULL),
('Смузи из манго вьетнамский', 'Vietnamese mango smoothie', 1, 80, 300, NULL),
('Снежок', 'Snezhok drink', 1, 80, NULL, NULL),
('Сникерс', 'Snickers', 0, 488, 50, NULL),
('Сода', 'Baking soda', 0, 0, NULL, NULL),
('Сода для выпечки', 'Baking soda for baking', 0, 0, NULL, NULL),
('Сода пищевая', 'Baking soda', 0, 0, NULL, NULL),
('Соевое молоко', 'Soy milk', 1, 35, NULL, NULL),
('Соевый соус', 'Soy sauce', 0, 53, NULL, NULL),
('Сок апельсиновый', 'Orange juice', 1, 45, NULL, NULL),
('Сок виноградный', 'Grape juice', 1, 60, 200, NULL),
('Сок гранатовый', 'Pomegranate juice', 1, 54, 200, NULL),
('Сок мультифрукт', 'Multifruit juice', 1, 48, 200, NULL),
('Сок томатный', 'Tomato juice', 1, 17, 200, NULL),
('Сок яблочный', 'Apple juice', 1, 46, NULL, NULL),
('Соль', 'Salt', 0, 0, NULL, NULL),
('Соль гималайская', 'Himalayan salt', 0, 0, NULL, NULL),
('Соль морская', 'Sea salt', 0, 0, NULL, NULL),
('Солянка', 'Solyanka', 0, 68, NULL, NULL),
('Солянка мясная', 'Meat solyanka', 0, 80, NULL, NULL),
('Солёные огурцы', 'Salted cucumbers', 0, 11, NULL, NULL),
('Сом', 'Catfish', 0, 115, NULL, NULL),
('Сом жареный', 'Fried catfish', 0, 160, NULL, NULL),
('Сом запеченный', 'Baked catfish', 0, 130, NULL, NULL),
('Сосиска в тесте', 'Sausage in dough', 0, 287, NULL, NULL),
('Сосиски молочные', 'Milk sausages', 0, 266, NULL, NULL),
('Соус барбекю', 'BBQ sauce', 0, 130, NULL, NULL),
('Соус кисло-сладкий', 'Sweet and sour sauce', 0, 150, NULL, NULL),
('Соус нуок чам', 'Nuoc cham', 0, 40, NULL, NULL),
('Соус рыбный', 'Fish sauce', 0, 35, NULL, NULL),
('Соус сырный', 'Cheese sauce', 0, 260, NULL, NULL),
('Соус сычуаньский', 'Sichuan sauce', 0, 120, NULL, NULL),
('Соус тартар', 'Tartar sauce', 0, 340, NULL, NULL),
('Соус терияки', 'Teriyaki sauce', 0, 89, NULL, NULL),
('Соус устричный', 'Oyster sauce', 0, 51, NULL, NULL),
('Соус хойсин', 'Hoisin sauce', 0, 220, NULL, NULL),
('Соус чили китайский', 'Chinese chili sauce', 0, 80, NULL, NULL),
('Соус шрирача', 'Sriracha', 0, 93, NULL, NULL),
('Соя', 'Soybeans', 0, 147, NULL, NULL),
('Спагетти', 'Spaghetti', 0, 158, NULL, NULL),
('Спаржа', 'Asparagus', 0, 20, NULL, NULL),
('Специи смесь', 'Spice mix', 0, 250, NULL, NULL),
('Спирулина', 'Spirulina', 0, 290, NULL, NULL),
('Спрайт', 'Sprite', 1, 39, 330, NULL),
('Спрей для выпечки', 'Baking spray', 0, 884, NULL, NULL),
('Стевия', 'Stevia', 0, 0, NULL, NULL),
('Стейк миньон', 'Filet mignon', 0, 267, NULL, NULL),
('Стейк рибай', 'Ribeye steak', 0, 291, NULL, NULL),
('Стейк свиной', 'Pork steak', 0, 250, NULL, NULL),
('Стерлядь', 'Sterlet', 0, 88, NULL, NULL),
('Стерлядь запеченная', 'Baked sterlet', 0, 110, NULL, NULL),
('Судак', 'Zander', 0, 84, NULL, NULL),
('Судак жареный', 'Fried zander', 0, 130, NULL, NULL),
('Судак запеченный', 'Baked zander', 0, 100, NULL, NULL),
('Судак на пару', 'Steamed zander', 0, 90, NULL, NULL),
('Сумах', 'Sumac', 0, 250, NULL, NULL),
('Суп грибной', 'Mushroom soup', 0, 40, NULL, NULL),
('Суп кисло-острый вьетнамский', 'Vietnamese sour spicy soup', 0, 50, NULL, NULL),
('Суп пюре', 'Cream soup', 0, 55, NULL, NULL),
('Суп с кисло-острыми нотками', 'Hot and sour soup', 0, 45, NULL, NULL),
('Суп с лапшой вьетнамский', 'Vietnamese noodle soup', 0, 55, NULL, NULL),
('Суп с лапшой китайский', 'Chinese noodle soup', 0, 60, NULL, NULL),
('Суп сырный', 'Cheese soup', 0, 80, NULL, NULL),
('Суп томатный', 'Tomato soup', 0, 35, NULL, NULL),
('Суп харчо', 'Kharcho', 0, 44, NULL, NULL),
('Суп яичный китайский', 'Egg drop soup', 0, 35, NULL, NULL),
('Сухари', 'Rusks', 0, 360, NULL, NULL),
('Сухари панировочные', 'Breadcrumbs', 0, 347, NULL, NULL),
('Сухарики', 'Crouton snacks', 0, 420, NULL, NULL),
('Сухие сливки', 'Powdered cream', 0, 500, NULL, NULL),
('Сухое молоко', 'Powdered milk', 0, 496, NULL, NULL),
('Суши', 'Sushi', 0, 150, NULL, NULL),
('Суши запеченные', 'Baked sushi', 0, 180, NULL, NULL),
('Суши запеченные с лососем', 'Baked salmon sushi', 0, 190, NULL, NULL),
('Суши запеченные с угрем', 'Baked eel sushi', 0, 210, NULL, NULL),
('Суши острые', 'Spicy sushi', 0, 170, NULL, NULL),
('Суши острые с лососем', 'Spicy salmon sushi', 0, 175, NULL, NULL),
('Суши острые с тунцом', 'Spicy tuna sushi', 0, 165, NULL, NULL),
('Суши с авокадо', 'Avocado sushi', 0, 140, NULL, NULL),
('Суши с гребешком', 'Scallop sushi', 0, 140, NULL, NULL),
('Суши с икрой', 'Roe sushi', 0, 160, NULL, NULL),
('Суши с кальмаром', 'Squid sushi', 0, 130, NULL, NULL),
('Суши с крабом', 'Crab sushi', 0, 145, NULL, NULL),
('Суши с креветкой', 'Shrimp sushi', 0, 140, NULL, NULL),
('Суши с лососем', 'Salmon sushi', 0, 160, NULL, NULL),
('Суши с лососем и авокадо', 'Salmon avocado sushi', 0, 165, NULL, NULL),
('Суши с мидиями', 'Mussel sushi', 0, 140, NULL, NULL),
('Суши с огурцом', 'Cucumber sushi', 0, 120, NULL, NULL),
('Суши с окунем', 'Perch sushi', 0, 145, NULL, NULL),
('Суши с осьминогом', 'Octopus sushi', 0, 130, NULL, NULL),
('Суши с тамаго', 'Tamago sushi', 0, 150, NULL, NULL),
('Суши с тобико', 'Tobiko sushi', 0, 150, NULL, NULL),
('Суши с тунцом', 'Tuna sushi', 0, 150, NULL, NULL),
('Суши с угрем', 'Eel sushi', 0, 200, NULL, NULL),
('Суши с форелью', 'Trout sushi', 0, 155, NULL, NULL),
('Суши сет', 'Sushi set', 0, 160, NULL, NULL),
('Суши сет большой', 'Large sushi set', 0, 165, NULL, NULL),
('Суши сет маленький', 'Small sushi set', 0, 155, NULL, NULL),
('Сушки', 'Sushki', 0, 370, NULL, NULL),
('Сыр адыгейский', 'Adyghe cheese', 0, 240, NULL, NULL),
('Сыр гауда', 'Gouda', 0, 356, NULL, NULL),
('Сыр моцарелла', 'Mozzarella', 0, 280, NULL, NULL),
('Сыр пармезан', 'Parmesan', 0, 392, NULL, NULL),
('Сыр плавленый', 'Processed cheese', 0, 257, NULL, NULL),
('Сыр российский', 'Russian cheese', 0, 363, NULL, NULL),
('Сыр сулугуни', 'Suluguni', 0, 290, NULL, NULL),
('Сыр творожный', 'Cream cheese', 0, 253, NULL, NULL),
('Сыр фета', 'Feta', 0, 264, NULL, NULL),
('Сыр чеддер', 'Cheddar', 0, 403, NULL, NULL),
('Сырники', 'Syrniki', 0, 220, NULL, NULL),
('Сырники со сметаной', 'Syrniki with sour cream', 0, 230, NULL, NULL),
('Сырок глазированный', 'Glazed curd bar', 0, 407, 50, NULL),
('Сычуаньская рыба', 'Sichuan fish', 0, 150, NULL, NULL),
('Сяолунбао', 'Xiaolongbao', 0, 200, NULL, NULL),
('Сёмга', 'Atlantic salmon', 0, 201, NULL, NULL),
('Сёмга горячего копчения', 'Hot-smoked Atlantic salmon', 0, 190, NULL, NULL),
('Сёмга копченая', 'Smoked Atlantic salmon', 0, 180, NULL, NULL),
('Сёмга слабосоленая', 'Lightly salted Atlantic salmon', 0, 202, NULL, NULL),
('Сёмга соленая', 'Salted Atlantic salmon', 0, 210, NULL, NULL),
('Сёмга холодного копчения', 'Cold-smoked Atlantic salmon', 0, 170, NULL, NULL),
('Тамаринд', 'Tamarind', 0, 239, NULL, NULL),
('Тан', 'Tan', 1, 20, 250, NULL),
('Танжерин', 'Tangerine', 0, 53, NULL, NULL),
('Тарань', 'Taran', 0, 88, NULL, NULL),
('Тарань вяленая', 'Dried taran', 0, 230, NULL, NULL),
('Таро', 'Taro', 0, 112, NULL, NULL),
('Таро шарики', 'Taro balls', 0, 150, NULL, NULL),
('Тацой', 'Tatsoi', 0, 20, NULL, NULL),
('Твикс', 'Twix', 0, 495, 50, NULL),
('Творог 0,5%', 'Cottage cheese 0.5%', 0, 90, NULL, NULL),
('Творог 2%', 'Cottage cheese 2%', 0, 103, NULL, NULL),
('Творог 5%', 'Cottage cheese 5%', 0, 121, NULL, NULL),
('Творог 9%', 'Cottage cheese 9%', 0, 159, NULL, NULL),
('Творог зерненый', 'Grainy cottage cheese', 0, 105, NULL, NULL),
('Творожная запеканка', 'Cottage cheese casserole', 0, 180, NULL, NULL),
('Творожная масса', 'Curd mass', 0, 280, NULL, NULL),
('Творожок детский', 'Children cottage cheese', 0, 100, NULL, NULL),
('Текила', 'Tequila', 1, 231, 50, NULL),
('Темаки', 'Temaki hand roll', 0, 160, NULL, NULL),
('Темаки с креветкой', 'Shrimp temaki', 0, 155, NULL, NULL),
('Темаки с лососем', 'Salmon temaki', 0, 170, NULL, NULL),
('Темаки с тунцом', 'Tuna temaki', 0, 165, NULL, NULL),
('Темпе', 'Tempeh', 0, 193, NULL, NULL),
('Тефтели', 'Meatballs', 0, 197, NULL, NULL),
('Тимьян', 'Thyme', 0, 101, NULL, NULL),
('Тимьян сушеный', 'Dried thyme', 0, 276, NULL, NULL),
('Тирамису', 'Tiramisu', 0, 290, NULL, NULL),
('Тмин', 'Caraway', 0, 333, NULL, NULL),
('Том ям', 'Tom yum', 0, 55, NULL, NULL),
('Томатильо', 'Tomatillo', 0, 32, NULL, NULL),
('Томатный сок', NULL, 1, 17, NULL, NULL),
('Тоник', 'Tonic water', 1, 34, 200, NULL),
('Топинамбур', 'Jerusalem artichoke', 0, 61, NULL, NULL),
('Торт Медовик', 'Honey cake', 0, 380, NULL, NULL),
('Торт Наполеон', 'Napoleon cake', 0, 400, NULL, NULL),
('Тортилья', 'Tortilla', 0, 300, NULL, NULL),
('Тосты', 'Toast', 0, 265, NULL, NULL),
('Тофу', 'Tofu', 0, 76, NULL, NULL),
('Тофу в кисло-сладком соусе', 'Sweet and sour tofu', 0, 110, NULL, NULL),
('Тофу жареный вьетнамский', 'Vietnamese fried tofu', 0, 150, NULL, NULL),
('Тофу копченый', 'Smoked tofu', 0, 140, NULL, NULL),
('Треска', 'Cod', 0, 82, NULL, NULL),
('Треска в кляре', 'Battered cod', 0, 200, NULL, NULL),
('Треска вареная', 'Boiled cod', 0, 80, NULL, NULL),
('Треска жареная', 'Fried cod', 0, 150, NULL, NULL),
('Треска запеченная', 'Baked cod', 0, 100, NULL, NULL),
('Треска копченая', 'Smoked cod', 0, 110, NULL, NULL),
('Треска на пару', 'Steamed cod', 0, 85, NULL, NULL),
('Треска слабосоленая', 'Lightly salted cod', 0, 90, NULL, NULL),
('Треска соленая', 'Salted cod', 0, 100, NULL, NULL),
('Тунец', 'Tuna', 0, 144, NULL, NULL),
('Тунец в масле', 'Tuna in oil', 0, 198, NULL, NULL),
('Тунец в собственном соку', 'Tuna in own juice', 0, 96, NULL, NULL),
('Тунец консервированный', 'Canned tuna', 0, 96, NULL, NULL),
('Тунец копченый', 'Smoked tuna', 0, 160, NULL, NULL),
('Тунец слабосоленый', 'Lightly salted tuna', 0, 150, NULL, NULL),
('Тунец стейк', 'Tuna steak', 0, 144, NULL, NULL),
('Тушенка говяжья', 'Canned stewed beef', 0, 220, NULL, NULL),
('Тушенка куриная', 'Canned stewed chicken', 0, 180, NULL, NULL),
('Тушенка свиная', 'Canned stewed pork', 0, 250, NULL, NULL),
('Тыква', 'Pumpkin', 0, 26, NULL, NULL),
('Тыква баттернат', 'Butternut squash', 0, 45, NULL, NULL),
('Тыква хаккадо', 'Hokkaido squash', 0, 45, NULL, NULL),
('Угорь', 'Eel', 0, 333, NULL, NULL),
('Удон', 'Udon', 0, 100, NULL, NULL),
('Укроп', 'Dill', 0, 38, NULL, NULL),
('Укроп сушеный', 'Dried dill', 0, 253, NULL, NULL),
('Уксус', 'Vinegar', 0, 18, NULL, NULL),
('Уксус бальзамический', 'Balsamic vinegar', 0, 88, NULL, NULL),
('Уксус яблочный', 'Apple cider vinegar', 0, 21, NULL, NULL),
('Универсальная приправа', 'All-purpose seasoning', 0, 200, NULL, NULL),
('Устрицы', 'Oysters', 0, 81, NULL, NULL),
('Устрицы запеченные вьетнамские', 'Vietnamese baked oysters', 0, 120, NULL, NULL),
('Утка', 'Duck', 0, 240, NULL, NULL),
('Утка по-пекински', 'Peking duck', 0, 280, NULL, NULL),
('Уха', 'Ukha', 0, 46, NULL, NULL),
('Уха царская', 'Tsar''s ukha', 0, 50, NULL, NULL),
('Уцхо-сунели', 'Utskho-suneli', 0, 250, NULL, NULL),
('Фанта', 'Fanta', 1, 46, 330, NULL),
('Фарш говяжий', 'Ground beef', 0, 254, NULL, NULL),
('Фарш куриный', 'Ground chicken', 0, 143, NULL, NULL),
('Фасоль вареная', 'Boiled beans', 0, 123, NULL, NULL),
('Фасоль красная', 'Red kidney beans', 0, 127, NULL, NULL),
('Фасоль стручковая', 'Green beans', 0, 31, NULL, NULL),
('Фасоль черная', 'Black beans', 0, 132, NULL, NULL),
('Фасоль эдамаме', 'Edamame', 0, 122, NULL, NULL),
('Фейхоа', 'Feijoa', 0, 49, NULL, NULL),
('Фенхель', 'Fennel', 0, 31, NULL, NULL),
('Фенхель семена', 'Fennel seeds', 0, 345, NULL, NULL),
('Физалис', 'Physalis', 0, 32, NULL, NULL),
('Филе минтая', 'Pollock fillet', 0, 72, NULL, NULL),
('Финики', 'Dates', 0, 282, NULL, NULL),
('Финики меджул', 'Medjool dates', 0, 277, NULL, NULL),
('Фо бо', 'Pho bo', 0, 45, NULL, NULL),
('Фо га', 'Pho ga', 0, 40, NULL, NULL),
('Фо с говядиной', 'Beef pho', 0, 45, NULL, NULL),
('Фо с курицей', 'Chicken pho', 0, 40, NULL, NULL),
('Форель', 'Trout', 0, 119, NULL, NULL),
('Форель горячего копчения', 'Hot-smoked trout', 0, 160, NULL, NULL),
('Форель жареная', 'Fried trout', 0, 170, NULL, NULL),
('Форель запеченная', 'Baked trout', 0, 140, NULL, NULL),
('Форель копченая', 'Smoked trout', 0, 150, NULL, NULL),
('Форель на пару', 'Steamed trout', 0, 120, NULL, NULL),
('Форель радужная', 'Rainbow trout', 0, 119, NULL, NULL),
('Форель слабосоленая', 'Lightly salted trout', 0, 130, NULL, NULL),
('Форель соленая', 'Salted trout', 0, 140, NULL, NULL),
('Форель холодного копчения', 'Cold-smoked trout', 0, 145, NULL, NULL),
('Форшмак', 'Forshmak', 0, 200, NULL, NULL),
('Фризе', 'Frisée', 0, 17, NULL, NULL),
('Фруктовый салат', 'Fruit salad', 0, 50, NULL, NULL),
('Фруктоза', 'Fructose', 0, 400, NULL, NULL),
('Халва', 'Halva', 0, 516, NULL, NULL),
('Хамса', 'European anchovy', 0, 135, NULL, NULL),
('Хамса соленая', 'Salted hamsa', 0, 150, NULL, NULL),
('Харчо', 'Kharcho soup', 0, 44, NULL, NULL),
('Хачапури', 'Khachapuri', 0, 270, NULL, NULL),
('Хашбраун', 'Hash browns', 0, 260, NULL, NULL),
('Хек', 'Hake', 0, 86, NULL, NULL),
('Хек жареный', 'Fried hake', 0, 150, NULL, NULL),
('Хек запеченный', 'Baked hake', 0, 100, NULL, NULL),
('Хек на пару', 'Steamed hake', 0, 90, NULL, NULL),
('Херес', 'Sherry', 1, 116, 50, NULL),
('Хинкали', 'Khinkali', 0, 234, NULL, NULL),
('Хлеб белый', 'White bread', 0, 265, NULL, NULL),
('Хлеб бородинский', 'Borodinsky bread', 0, 208, NULL, NULL),
('Хлеб ржаной', 'Rye bread', 0, 201, NULL, NULL),
('Хлеб цельнозерновой', 'Whole grain bread', 0, 250, NULL, NULL),
('Хлебное дерево', 'Breadfruit', 0, 103, NULL, NULL),
('Хлебцы', 'Crispbread', 0, 310, NULL, NULL),
('Хмели-сунели', 'Khmeli-suneli', 0, 250, NULL, NULL),
('Хмели-сунели смесь', 'Khmeli-suneli mix', 0, 250, NULL, NULL),
('Холодец', 'Kholodets', 0, 100, NULL, NULL),
('Холодец говяжий', 'Beef kholodets', 0, 100, NULL, NULL),
('Холодец свиной', 'Pork kholodets', 0, 120, NULL, NULL),
('Хот-дог', 'Hot dog', 0, 290, NULL, NULL),
('Хрен', 'Horseradish', 0, 48, NULL, NULL),
('Хрен корень', 'Horseradish root', 0, 48, NULL, NULL),
('Ху тиеу', 'Hu tieu', 0, 100, NULL, NULL),
('Хумус', 'Hummus', 0, 166, NULL, NULL),
('Хурма', 'Persimmon', 0, 127, NULL, NULL),
('Цветная капуста', 'Cauliflower', 0, 30, NULL, NULL),
('Цитрон', 'Citron', 0, 40, NULL, NULL),
('Цукаты', 'Candied fruit', 0, 320, NULL, NULL),
('Цуккини жареный', 'Fried zucchini', 0, 90, NULL, NULL),
('Ча гио', 'Cha gio', 0, 250, NULL, NULL),
('Ча ка', 'Cha ca', 0, 140, NULL, NULL),
('Ча луа', 'Cha lua', 0, 160, NULL, NULL),
('Ча сиу бао', 'Char siu bao', 0, 240, NULL, NULL),
('Чавыча', 'Chinook salmon', 0, 179, NULL, NULL),
('Чавыча слабосоленая', 'Lightly salted chinook', 0, 190, NULL, NULL),
('Чай жасминовый', 'Jasmine tea', 1, 1, 200, NULL),
('Чай зеленый без сахара', 'Green tea no sugar', 1, 1, NULL, NULL),
('Чай лотоса', 'Lotus tea', 1, 1, 200, NULL),
('Чай молочный пузырьковый', 'Bubble tea', 1, 80, 400, NULL),
('Чай пуэр', 'Pu-erh tea', 1, 1, 200, NULL),
('Чай с жасмином вьетнамский', 'Vietnamese jasmine tea', 1, 1, 200, NULL),
('Чай улун', 'Oolong tea', 1, 1, 200, NULL),
('Чай черный без сахара', 'Black tea no sugar', 1, 1, NULL, NULL),
('Чайот', 'Chayote', 0, 19, NULL, NULL),
('Чача', 'Chacha', 1, 230, 50, NULL),
('Чебурек', 'Cheburek', 0, 290, NULL, NULL),
('Черемуха', 'Bird cherry', 0, 50, NULL, NULL),
('Черемша', 'Wild garlic', 0, 35, NULL, NULL),
('Черешня', 'Cherry', 0, 50, NULL, NULL),
('Черимойя', 'Cherimoya', 0, 75, NULL, NULL),
('Черная смородина', 'Black currant', 0, 44, NULL, NULL),
('Черника', 'Bilberry', 0, 44, NULL, NULL),
('Чернослив', 'Prunes', 0, 256, NULL, NULL),
('Чернослив без косточки', 'Pitted prunes', 0, 240, NULL, NULL),
('Чеснок', 'Garlic', 0, 143, NULL, NULL),
('Чеснок гранулированный', 'Garlic granules', 0, 331, NULL, NULL),
('Чеснок жареный', 'Fried garlic', 0, 200, NULL, NULL),
('Чеснок молодой', 'Young garlic', 0, 100, NULL, NULL),
('Чеснок сушеный', 'Dried garlic', 0, 331, NULL, NULL),
('Чечевица вареная', 'Boiled lentils', 0, 116, NULL, NULL),
('Чечевица зеленая', 'Green lentils', 0, 116, NULL, NULL),
('Чечевица красная', 'Red lentils', 0, 116, NULL, NULL),
('Чизбургер', 'Cheeseburger', 0, 303, NULL, NULL),
('Чизкейк', 'Cheesecake', 0, 321, NULL, NULL),
('Чили порошок', 'Chili powder', 0, 282, NULL, NULL),
('Чипсы', 'Chips', 0, 510, NULL, NULL),
('Чипсы картофельные', 'Potato chips', 0, 520, NULL, NULL),
('Чипсы кукурузные', 'Corn chips', 0, 500, NULL, NULL),
('Чука', 'Chuka seaweed salad', 0, 70, NULL, NULL),
('Чуфа', 'Tiger nut', 0, 400, NULL, NULL),
('Чэ', 'Che dessert', 0, 120, NULL, NULL),
('Шампанское', 'Champagne', 1, 88, 150, NULL),
('Шампиньоны', 'Mushrooms', 0, 22, NULL, NULL),
('Шаурма', 'Shawarma', 0, 174, NULL, NULL),
('Шаурма с говядиной', 'Beef shawarma', 0, 192, NULL, NULL),
('Шаурма с курицей', 'Chicken shawarma', 0, 180, NULL, NULL),
('Шафран', 'Saffron', 0, 310, NULL, NULL),
('Шашлык из баранины', 'Lamb kebab', 0, 250, NULL, NULL),
('Шашлык из курицы', 'Chicken kebab', 0, 142, NULL, NULL),
('Шашлык из свинины', 'Pork kebab', 0, 326, NULL, NULL),
('Шелковица', 'Mulberry', 0, 43, NULL, NULL),
('Шиповник', 'Rose hip', 0, 109, NULL, NULL),
('Шницель', 'Schnitzel', 0, 270, NULL, NULL),
('Шоколад молочный', 'Milk chocolate', 0, 535, NULL, NULL),
('Шоколад темный', 'Dark chocolate', 0, 539, NULL, NULL),
('Шоколадная крошка', 'Chocolate chips', 0, 500, NULL, NULL),
('Шпик', 'Speck', 0, 750, NULL, NULL),
('Шпинат бэби', 'Baby spinach', 0, 23, NULL, NULL),
('Шпинат зеленый', 'Green spinach', 0, 22, NULL, NULL),
('Шпроты', 'Sprats', 0, 363, NULL, NULL),
('Шпроты в масле', 'Sprats in oil', 0, 363, NULL, NULL),
('Шпроты копченые', 'Smoked sprats', 0, 250, NULL, NULL),
('Щи', 'Shchi', 0, 31, NULL, NULL),
('Щи из свежей капусты', 'Fresh cabbage shchi', 0, 31, NULL, NULL),
('Щи кислые', 'Sour shchi', 0, 35, NULL, NULL),
('Щука', 'Pike', 0, 84, NULL, NULL),
('Щука жареная', 'Fried pike', 0, 130, NULL, NULL),
('Щука запеченная', 'Baked pike', 0, 100, NULL, NULL),
('Эклер', 'Eclair', 0, 330, NULL, NULL),
('Эндивий', 'Endive', 0, 17, NULL, NULL),
('Энергетический напиток', 'Energy drink', 1, 45, 250, NULL),
('Эритрит', 'Erythritol', 0, 0, NULL, NULL),
('Эспрессо', 'Espresso', 1, 9, 30, NULL),
('Эстрагон', 'Tarragon', 0, 295, NULL, NULL),
('Юдзу', 'Yuzu', 0, 40, NULL, NULL),
('Юка', 'Yuca', 0, 160, NULL, NULL),
('Яблоко', 'Apple', 0, 47, NULL, NULL),
('Яблоко зеленое', 'Green apple', 0, 52, NULL, NULL),
('Яблоко красное', 'Red apple', 0, 52, NULL, NULL),
('Яичница глазунья', 'Fried eggs', 0, 196, NULL, NULL),
('Яичные роллы', 'Egg rolls', 0, 240, NULL, NULL),
('Яичный порошок', 'Egg powder', 0, 542, NULL, NULL),
('Яйцо вареное', 'Boiled egg', 0, 155, NULL, NULL),
('Яйцо вкрутую', 'Hard-boiled egg', 0, 155, 55, NULL),
('Яйцо всмятку', 'Soft-boiled egg', 0, 155, 55, NULL),
('Яйцо перепелиное', 'Quail egg', 0, 168, 12, NULL),
('Яйцо сырое', 'Raw egg', 0, 157, 55, NULL),
('Ямс', 'Yam', 0, 118, NULL, NULL),
('Ячневая каша', 'Barley porridge', 0, 100, NULL, NULL);

